### ISSUE TITLE
Notification Count

### ISSUE THREAD

**Issue by lordofentropy314** [fetlife/android#262] opened 2017-01-18 15:29 UTC
In v2.3.0 the app's notification count is frozen on 1 when there isn't any new notifications.

**Comment by kistitan** [comment] 2017-01-18 21:28
Hi @lordofentropy314,

Thank you for reporting this issue.
Would you mind if I ask for a bit more details?

You received a notification in the notification bar and after did you open the app by clicking on the notification or from your app list?

Notification disappears only if you click on it or dismiss it in the notification bar.
Opening the app any other way won't make the notification disappear by automatically.

**Comment by lordofentropy314** [comment] 2017-01-18 21:32
As in right after I installed this version, the counter displays a 1 by the
app's icon, however there was never a new notification, as in nothing new
happen to generate and trigger the counter/flag.

Mark Roberts
Senior Research/Design Scientist of Nuclear Physics at Florida State
University

"Something Infinite can not exist in a finite world."
Mark Roberts

"If we knew what we were doing, it wouldn't be called research, would it?"
Albert Einstein

"One thing they don't tell you about doing experimental physics is that
sometimes you must work under adverse conditions ... like a state of sheer
terror."
W. K. Hartmann

**Comment by Kurisu86** [comment] 2017-01-18 21:40
I am experiencing the same issue. Installed the update and had 1 new notification indicator by the App's icon. Checked on mobile, desktop, and in app to find no new notification. Rebooting phone did not change it either.

**Comment by kistitan** [comment] 2017-01-18 21:56
Hmm...
Actually we do not have app icon counter feature implemented in the app.
Do you guys use custom launcher? Or does your App manufacturer has this feature by default?

**Comment by xeroace** [comment] 2017-01-19 18:06
I'm doing everything with the default app and I have the "1" notification as well. Galaxy 5

**Comment by kistitan** [comment] 2017-01-23 09:29
Hi @lordofentropy314 , @Kurisu86 , @xeroace 

I am sorry that you all face this issue.
It is difficult from this side as it connected to a feature that is provided by Samsung (or other manufacturer) and not part of standard Android so we have lack of knowledge about the details.
If you google for it you can see several threads about stucked notification count with different apps even with gmail. 

So we are in a little bit in dark here but we will figure it out.

As a first step can you please try the following workaround: 
- Start the FetLife App
- Go to Settings > General Settings > Change the checkbox for "Go Vanilla" Setting
- Go back to your home screen, and re launch your app browser until you see the app icon has been changed (From FetLife logo to FL or vica versa)
- Repeat the same changing back your App icon to the original one

Please let me know if:
- it solved the issue
- it solved completely or after a while it stuck again

Thank you

**Comment by benjaminarthurt** [comment] 2017-01-31 11:56
I was experiencing the same issue, checking "go vanilla" removed the indicator. I tried switching back and the indicator returned. So far, with using it in vanilla mode there is no "1" indicator. Using latest beta v2.4.0

**Comment by lordofentropy314** [comment] 2017-02-03 14:13
I tried all those previous suggestions, however it would just come back on
the version before v2.4.0.

In v2.4.0 there are no issues for me, samsung galaxy 6 edge.

Mark Roberts
Senior Research/Design Scientist of Nuclear Physics at Florida State
University

"Something Infinite can not exist in a finite world."
Mark Roberts

"If we knew what we were doing, it wouldn't be called research, would it?"
Albert Einstein

"One thing they don't tell you about doing experimental physics is that
sometimes you must work under adverse conditions ... like a state of sheer
terror."
W. K. Hartmann

**Comment by kistitan** [comment] 2017-02-06 19:14
Hi all,

After some investigation incorrect badge count is relatively frequent for many different apps like whatsapp, gmail etc.
It is said to be a device issue usually.
Even if I cannot make statement like that usually, what I can see that we do not really have a code change that should anyhow connected to this issue.

Whatsapp also have a specific FAQ solution for this issue. 
Most of their suggestion can be done with the FetLife App too actually.
Can you please take a look at these option and check if they work for you?

Thanks a lot:

https://www.whatsapp.com/faq/en/android/28000014

**Comment by Kurisu86** [comment] 2017-02-06 22:09
Go to Settings > Device > Applications > Application manager > FetLife > Storage and tap Clear Data

The above worked for me. The extra notification badges went away after I logged back into the app.

**Comment by kistitan** [comment] 2017-02-06 23:03
That's good news. Thanks for checking!

**Comment by kistitan** [comment] 2017-02-14 19:17
Issues is closed as the solution above worked.

**Comment by malachid** [comment] 2017-02-14 19:27
Clearing the data is not a valid solution.  Mine consistently says I have 1 notification. I am not going to clear the app data (including saved password) every single time I read a notification.

**Comment by kistitan** [comment] 2017-02-14 19:35
@malachid

I do understand. However we do not mess at all with the notification count of samsung.
And appearently same issue apears with many different apps for different users (whatsapp, gmail, facebook.. you can find them in their FAQ).

As a user you are totally right. As a developer what do you suggest?

Btw can you confirm that after deleting clearing the data once, issue reappear anytime soon again?

Thank you!

**Comment by thezerogod** [comment] 2017-02-14 19:54
Have you considered using the notification options in OneSignal to disable
icon badges entirely?

https://documentation.onesignal.com/docs/android-customizations#section-app-icon-badge-counts

**Comment by kistitan** [comment] 2017-02-14 20:05
Would you prefer not having it at all than rather having it with sometimes stucked in value?

Btw could you really help me out how serious this issue is?
I tried to reproduce it with a Samsung device but even after significant usage it worked for me perfectly.

So from your messages (and in general comments about similar issues with other apps) I got the impression that it happens once in a while than it can let it get with data clear.
Based on this it seems to be low priority.

But based on malachid comment it kind of occured even right after the data has cleared.


What actually I can still do is to get in contact with OS support to discuss if they have any idea.
However we already have a very long due issue with them , so indeed native replacements is also something to be considered.

**Comment by thezerogod** [comment] 2017-02-14 20:11
I'm not experiencing this issue (I use the Google Nexus default launcher,
which does not have badges for app icons), but if I were this would be a
significant annoyance to me - and yes, I would prefer that the app not
support badges rather than having an incorrect badge count.

**Comment by malachid** [comment] 2017-02-14 20:33
I'm not using a Samsung device. I am on LG v10. This bug only appears on this app. The other apps do not have this problem.

I did not clear my data. I assume that will work as it deletes everything. I was pointing out that deleting everything is not a valid solution as it would require entering your password every time.

**Comment by Kurisu86** [comment] 2017-02-14 22:55
Clear it once and that's all you need. You'll be able to have it remember
your password in the future, just like the first time. The issue has not
occurred again for me.

**Comment by kistitan** [comment] 2017-02-15 08:04
Yes, I agree it is not a solution, but if there is an issue with Samsung badge system, we cannot solve but give a workaround suggestion.

Turning off the badge notification fully is an obvious solution if the indication is totally broken.
But based on the feedback it is not.

On the other hand your comments actually helped me not to give it up that early and push it further with the investigation and now I am not that sure any more about that this is the general Samsung issue.
Even if we don't do anything with that notification count, One Signal library might do actually.
Furthermore we have already an old ongoing open ticket for them about failed notification. And this can actually very much related.

So I will add a workaround that might or might not help and pushing the investigation at OneSignal with these new concerns.

Thanks again for all of you again for being part of our team with all your useful remarks concerns and suggestions.
Keep them coming!

**Comment by kistitan** [comment] 2017-02-20 08:24
Based on the information we have we probably managed to find the reason in a one signal bug.
We added a workaround until one signal fix their bug, so I close this issue now as we have an ongoing thread about this at their repository.

However as I could not reproduce I could not test so fee free to reopen if it still occur frequently (if it happens very rare it still can be the known samsung issue mentioned above).

Note: after using the new version you should still clean the data of the app and login again ONCE.
Hopefully after it will all work fine.

Thanks all.

Changes are in version 2.5.8

**Closed by kistitan** 2017-02-20 08:24 UTC
Labels: in progress, question, waiting for release
