### ISSUE TITLE
Friend's profile still visible in app after they've deactivated it.

### ISSUE THREAD

**Issue by entropybound** [fetlife/android#360] opened 2017-10-09 18:20 UTC
A friend of mine needed to de-activate their profile for personal reasons.  I noticed that for a while, in the app, I could still see their profile and all of the pictures/statuses they had posted.  When on a desktop/web interface, all of that content was not visible.   Additionally, when I would browse the profile on the app, I would see "Connection failed. Please try again later", telling me that what I was viewing was a local cached copy.  

Eventually that cache on the app expired and while all of the tabs (basic info, about, statuses, etc.) were empty, I can still see the profile picture, handle, age, gender, and identity.  This leads to an interesting point; shouldn't the app proactively clear that cache when the profile gets disabled so that other people cant access the content?  Additionally, shouldn't the app prevent from seeing the profile at all?

Thanks for all the awesome work on the app! It's really come into its own in the past year!

**Comment by kistitan** [comment] 2017-10-11 14:06
Hi @entropybound ,

That is actually true that we do not have a push notification from the server when actually a use get deactivated, so indeed some of their previous public (to that specific user) information remain in the cache for a while.
It would be nice to be able to notify the app right away when a user is deleted so the cache can be invalidated. We will investigate this possibility.

Otherwise based on the current devices, as references to the given member (like in your friend list etc) will be continuously synced after a while all references to that given member will be invisible also in the app so at the end also the cached user data will be removed.
If it is not happening (e.g. you can still see the deleted user in your friend list) please let us know.

I keep this issue open as we have definitely room for improvement in this topic.

Thanks you for your kind words about the app :)

**Comment by LokiTheWanderer** [comment] 2017-11-22 18:17
I'm having the same issue.  In some cases, the profiles have been inactive for over a year, yet they still appear on my list in the app.

**Comment by CyBradMachina** [comment] 2018-01-23 19:46
I still see this issue currently i have a specific friend whom her account was deleted by caretakers telling her to prove that she is who she said she was and that's been over 6 months now and her profile still appears in my friends list, also oddly let's say one user blocks another user the blocked user can tell if the person that blocked them is still on FetLife via the app only vs if a person deleted their account or was removed by admins or whatever won't show up in app's member search whereas users having (let's use me as an example) blocked me i can search their username and still see they have an account on FetLife.

That said is this a bug? Or an intentional loop hole?

**Comment by kistitan** [comment] 2018-01-23 20:02
@CyBradMachina

It is definitely a bug on our side.
Some sync time is acceptable but deactivated users should disappear after a while.

The bug is still there because I still could not reproduce it locally so I could not debug it so far.
I am really so for that.

If it is really bothering would you mind going to the Settings / Profile Settings and select : Clear local User Data. That will remove all the cached data from your device.

I hope I will be able to reproduce the issue soon and I can figure out what's going wrong

**Comment by flgnl** [comment] 2018-03-01 18:59
I can confirm this. And clearing all the app data (both from the app itself and from the Android settings) does not remove the inactive users (or deleted, I wouldn't know) from my friends list. I can still see profile pictures and nicks when I open their profiles. Apart from that I get a connection error. It looks like inactive users are retrieved along with my active friends.

So it's not a caching issue, it's an API issue.

**Comment by kistitan** [comment] 2019-03-07 14:31
Merging into https://github.com/fetlife/android/issues/496

**Closed by kistitan** 2019-03-07 14:31 UTC
Labels: GitHub Only, Investigation, Priority 3, bug
