### ISSUE TITLE
.17 fails to connect 

### ISSUE THREAD

**Issue by FernandoMiguel** [fetlife/android#183] opened 2016-09-30 15:45 UTC
![screenshot_20160930-164406](https://cloud.githubusercontent.com/assets/168366/18997639/3f0a1550-872d-11e6-95db-040c21df3f05.png)
![screenshot_20160930-164400](https://cloud.githubusercontent.com/assets/168366/18997645/455c3190-872d-11e6-9f3b-ec6e4fb86fc7.png)

**Comment by thezerogod** [comment] 2016-09-30 15:47
I've had the same issue; logging ou of the app from the hamburger menu hen
logging back in appears to resolve it.


mxter zero
zero@mxterzero.com

**Comment by FernandoMiguel** [comment] 2016-09-30 15:49
Alright... Log out and login
Now need some new notifications 

PS the front page needs to be updated to this release, tried to branch master but couldn't

**Comment by kistitan** [comment] 2016-09-30 16:24
Hi guys,

Thanks for reporting this issue.
I am happy to have a workaround however it is strange why did it happen.
I wonder if other users had the same issue too.
Especially because actually nothing login or user related changes in this version...

@FernandoMiguel 
Thanks for the reminder.
I am going to update it.

**Comment by kistitan** [comment] 2016-09-30 16:30
I tried to install to earlier versions and upgrade, but could not reproduce the issue.
If you see any similar please let me know about, any details could help.

**Comment by GojuSuzi** [comment] 2016-10-01 19:59
Had the same issue. The conversations that were there before the update would load, but still get the "connection failed" error and no new messages in. Would still work if I access a new message through the notification when it pops up, but loading the app cold couldn't pull anything new. 

And ditto on logging out then in fixing it.

**Comment by kistitan** [comment] 2016-10-02 02:49
Hmmm... Indeed something to be tracked down than.
From which version did you upgrade from?

**Comment by thezerogod** [comment] 2016-10-02 03:08
I've installed every version that's been released, so for me the upgrade
was from 1.7.12, and 1.7.0 before that

**Comment by kistitan** [comment] 2016-10-07 17:24
Still happening.
Probably tokens cannot be refreashed after expiration. 
Priority increased.

**Comment by kistitan** [comment] 2016-10-12 14:00
Issue occurred due the issues with token renewal.
Fixed in v 1.7.18

**Closed by kistitan** 2016-10-12 14:00 UTC
Labels: bug, priority high
