### ISSUE TITLE
2.17.6 Notifications continue to pop up 

### ISSUE THREAD

**Issue by ImperfMage** [fetlife/android#485] opened 2018-09-15 16:59 UTC
So here are my settings https://imgur.com/gallery/5c1Ew0u

And that I am still getting notifications with someone comments on a thread I have previously commented on

**Comment by Florastor** [comment] 2018-09-18 04:04
I have been having the same issues with persistent notifications when someone comments on a thread I have previously commented on. I have turned off all notifications and those particular notifications keep coming up. 

Just to check, I logged off from my account, still received the same notifications. Next, I cleared all the app data and still received the same notification. 

If it helps I am running a Moto Z2 Force on T-Mobile with Android version 8.0.0 w/ security patch level: May 1, 2018

**Comment by kistitan** [comment] 2018-09-18 06:01
Hi there,

Thank you for reporting this issue, we are trying to find the possible reason.
We will keep you updated.

Thanks for your patience.

**Comment by kistitan** [comment] 2018-09-28 12:13
Hi guys,

I am sorry for the late reply.
I tried to reproduce the issue on local test devices, but with the same settings (comment and group discussion notifications turned off) as you presented in the screenshot notifications got filtered out for me.
Which means I am a bit puzzled on this.
Would you mind trying the following (just in case preferences are not correctly saved on your device):
Go to your device's settings / app / FetLife / Storage -> Clear All Data.

Than start the FetLife App (you have to login again) go to your settings and disable again the Comments and Group Discussions Notifications Settings.

And let me know if anything changed in the behaviour.

Thanks for your help and patience.

**Comment by kistitan** [comment] 2018-09-28 12:18
If it does not help can you please also point to the concrete thread(s) that you are keep receiving notifications from? (Maybe the issue is somehow to related to some types of threads).

If you do not feel like pointing on it publicly, please feel free to send me in private message (user Dreamlite on Fetlife or krisztian@fetlife.com in email)

Thank you

**Comment by Florastor** [comment] 2018-10-02 23:15
> Hi guys,
> 
> I am sorry for the late reply.
> I tried to reproduce the issue on local test devices, but with the same settings (comment and group discussion notifications turned off) as you presented in the screenshot notifications got filtered out for me.
> Which means I am a bit puzzled on this.
> Would you mind trying the following (just in case preferences are not correctly saved on your device):
> Go to your device's settings / app / FetLife / Storage -> Clear All Data.
> 
> Than start the FetLife App (you have to login again) go to your settings and disable again the Comments and Group Discussions Notifications Settings.
> 
> And let me know if anything changed in the behaviour.
> 
> Thanks for your help and patience.

Sorry it has taken so long to get back to you. So when I had the issue with notifications I cleared all the data after I logged off from the app. It was still giving me notifications just for Group Discussions Notifications (at this point, I unchecked all notifications before logging out of the app). 

At that point I uninstalled the app for a few days and reinstalled and updated to v2.17.13.

No issues with rouge notifications, but now I get no notifications from the app. 

I am going to log out, clear data, and uninstall the app and the reinstall. 

I will make a new issues thread if there is not one already, if the issue is still there after the install.  

I appreate you getting back to me

**Comment by kistitan** [comment] 2018-10-03 11:54
Hi @Florastor ,

Getting no notifications is weird :(
Can you please double check also your settings at the webpage?

I know it is misleading texting but "web" notification checkboxes also effect on notifications that arrive to Android.

Thank you

**Comment by Florastor** [comment] 2018-10-03 19:44
Hey @kistitan, 

I double checked my notifications setting on the web, and everything is checked but the group notifications (which I make sure are checked off). The only reasons I realized I was not getting any notifications on the app; I received a few email notifications about the private messages, and the app did not notify me at all.

**Comment by Florastor** [comment] 2018-10-08 22:08
@kistitan 

Just an update. I cleared data and reinstalled the app and then installed v2.17.13 from the prompt in the app. Notifications are working for me again.

**Comment by kistitan** [comment] 2018-10-31 10:24
Thanks for letting us know, closing this issue now.

**Closed by kistitan** 2018-10-31 10:24 UTC
Labels: Investigation
