### ISSUE TITLE
new version doesn't sign in

### ISSUE THREAD

**Issue by BullDaddy** [fetlife/android#282] opened 2017-03-24 01:27 UTC
Just downloaded today's version  (can't get the version number as it keeps crashing) and it crashes on all logon attempts.  Running android version 7.0

**Comment by mocafet** [comment] 2017-03-24 01:33
@bulldaddy

Try going Into your Android settings then app manager. Touch the fetlife app and try clearing the data and cache. 

Worked for me!

**Comment by mocafet** [comment] 2017-03-24 01:34
![screenshot_20170323-230414](https://cloud.githubusercontent.com/assets/24795197/24276950/18a7c366-101d-11e7-8497-0a370bb70218.png)

**Comment by kistitan** [comment] 2017-03-24 08:25
Hi @BullDaddy ,

We are really sorry for the inconveniences.
This is a serious bug that we do not find the reason for yet.
But @mocafet is right, cleaning the App data is working workaround at this moment.
Obviously we are also working on to find the root cause for the issue in the meantime.

Thank you for your understandings!

**Comment by kistitan** [comment] 2017-03-26 09:01
Hi all,

Issue seems to be solved in 2.6.11.
Please let us know if this is not the case otherwise we can close this issue now :)

Thanks

**Closed** 2017-04-01 07:25 UTC
Labels: bug, Priority 0
