### ISSUE TITLE
Still some update issues.

### ISSUE THREAD

**Issue by calvinwiii** [fetlife/android#521] opened 2019-02-08 22:16 UTC
I have fetlife in a note 9 samsung protected folder.
App noted and downloaded new version. Could not load downloaded app from tool bar, but was able to find it in the download directory and load it manually. It did properly load in the protected folder. The new version launches without a new version message, however the check for updates menu item wants to reload the same version. I notice the download is 2.21.20, but in the app its listed as 2.21.2

**Comment by FernandoMiguel** [comment] 2019-02-09 08:05
This is a dupe of
https://github.com/fetlife/android/issues/517

The suffix zero issue is a funny one 
Programming is hard

**Comment by kistitan** [comment] 2019-02-20 08:32
Merging this into https://github.com/fetlife/android/issues/517>
Please follow answer there

**Closed by kistitan** 2019-02-20 08:32 UTC
