### ISSUE TITLE
v1.7.17 Issues

### ISSUE THREAD

**Issue by MyRenovatio** [fetlife/android#186] opened 2016-10-05 18:45 UTC
Overall, great app, but having a couple issues. Running on Galaxy S5 under Marshmallow 6.0.1
- Discussions that are archived due to blocking someone do not show the "you cannot respond to this notification..." line. Not really a big deal, but has me wondering if its seeing it as archived.
- Deleted conversations are showing up on the app conversation list. These conversations do not show up when logging in through the web.
- After viewing deleted or archived conversations, using either the menu or the phones back button results in a log out. Does not appear to happen with "active" conversations.
- When logging in, if you provide the wrong password, the on-screen keyboard disappears. Not sure if the removal is a trigger event for the the log in button, but it would be nice if the keyboard stayed up until you were actually authenticated.

Thanks!

**Comment by kistitan** [comment] 2016-10-11 12:51
@MyRenovatio

First of all sorry for the late reply.

Thanks a lot for using the app and reporting these issues.

Disappearing keyboard during logon is intentional as there are some information under the keyboard (on smaller screen sizes) that can be important in case of failed login.

Currently the app synchronize all active conversations by default and store them in local database for faster access. 
If the conversation get deleted after, the app doesn't get notification about so it will be still shown in the list.
We already have an open issues about this behavior.

The logout issue from deleted conversation however is strange. We have to look into it and try to reproduce it.

Thanks again

**Comment by kistitan** [comment] 2016-10-20 08:38
Hi there,

I could not reproduce this issue
"After viewing deleted or archived conversations, using either the menu or the phones back button results in a log out. Does not appear to happen with "active" conversations."

Can somebody please confirm if it still does occur sometimes or not?

**Comment by xShaithx** [comment] 2016-10-29 17:37
Yes, this will still happen. 

Close app. 
Log into website. 
Archive conversation. 
Log into app. 

Archived conversation still appears in the list.

**Comment by xShaithx** [comment] 2016-10-29 17:37
Still happens with deleted conversations as well.

**Comment by kistitan** [comment] 2016-11-01 10:59
@xShaithx 

Thank you.
We are working on keeping our local data consistent with online database.
This would solve the issue with not having archived conversations in the list.
However it needs some architectural design, so we have to ask four your patience.

Thank you

**Comment by kistitan** [comment] 2016-12-08 09:08
Hi there issue has been fixed and going to be part of the next release.
I close this issue now as we have other to track this issue,
Thank you for your patience.

**Closed by kistitan** 2016-12-08 09:08 UTC
Labels: bug, Priority 2
