### ISSUE TITLE
Show all conversations in app

### ISSUE THREAD

**Issue by ironjan** [fetlife/android#316] opened 2017-06-16 18:26 UTC
The web site distinguishes between "inbox" and "all conversations". The latter also shows messages that were sent but not answered. The app seems to show a mixture of both:

* Inbox messages are shown
* Messages sent via app are shown, even without answer
* Messages sent via web are only shown when answered (i.e. they're in the inbox)

This led to some confusion as I re-sent a message I had sent via web site before because I didn't see it in the app. I'd recommend that the app shows all conversations, regardless of how they are sent or wether they've been answered. 

app version: v2.8.1

*Edits:* Clarified the description, added app version

**Comment by kistitan** [comment] 2017-06-19 16:51
Hi @ironjan 

Thank you for reporting this issue.
Unfortunately I have to say this works as designed due to some limitations about how the website handles unanswered conversations.
It definitely could use some refactor, so I keep this issue open, but due to the complexity probably it won't happen in short term :(

**Comment by ironjan** [comment] 2017-06-22 10:06
Thanks for the information. I also noticed that the messaging system in the web app is very unusual for a social network. It's more like email or forum messages but unlike most social networks I know (facebook, Google+, twitter, …). If I've got the time I'll take a look at this (probably in 1-2 weeks the earliest).

**Comment by Germanbight** [comment] 2017-07-29 09:01
This may have been tackled in an earlier post. Wondering if you'd consider only showing live messages in the 'conversation. ' Archived messages and messages sent to users no longer following or friends confuse the page.

**Comment by Germanbight** [comment] 2017-07-30 22:33
Further, 
Messages deleted on the Web are still visible on the app, app is becoming over full of old and irrelevant messages.

**Comment by kistitan** [comment] 2017-08-01 17:54
Hi @Germanbight ,

Conversations in the App are cashed so until you start the App next time and go through the list with working connection they are visible.
Requesting the conversation from the server should made the not matching ones removed.
If this is the case it is an issue with the App.

In this second case can you please send me your nickname and the removed conversation ID (visible in the url) in private?
dreamlite@fetlife.com.

Thank you

**Comment by kistitan** [comment] 2018-10-29 09:53
As we are going to have webview based conversations screen in the near future, this issue will be automatically solved.
Closing this for now.

**Closed by kistitan** 2018-10-29 09:53 UTC
Labels: Priority 3, feature
