### ISSUE TITLE
Not seeing when I have notifications 

### ISSUE THREAD

**Issue by aimhigh76** [fetlife/android#371] opened 2017-10-29 07:56 UTC
I'm not able to see my notifications. Such as comments and likes on the newest app I have vs 2.11.11 android app. Ty

**Comment by kistitan** [comment] 2017-10-29 22:54
Hi @aimhigh76 ,

Thank you for reporting this issue.
Please let me ask for some more clarifications.

You do not receive the notifications at all or they are just not visible when they arrive?
(E.g. they are not visible on your lock screen but after unlocking you can see them)

Or you receiving them but your notifications screen is empty?

Thank you

**Comment by rudyvarner** [comment] 2017-11-07 01:18
I have the same problem. I get notifications for friend requests, new messages and group updates, but nothing for like and comments on pictures, writings  etc

**Comment by kistitan** [comment] 2017-11-08 11:16
Hi @rudyvarner,

Thank you for adding this comment.
As we cannot reproduce the issue, would you mind to do a bit of investigation?
As a first step would you mind checking:
- if all web notifications are turned on at the settings of Fetlife web page?
- if all notifications are turned on at the App's own settings?

Thank you

**Comment by kistitan** [comment] 2017-11-15 09:49
Issue still could not be reproduced, does anybody has an update?

**Comment by kamakazi414** [comment] 2017-11-21 02:13
Using v 2.11.15 I've lost my notifications of new private messages. In conversations,  I get the red&white NEW message. 

What I'm missing is the audio sound and the icon that appears in the android notification bar at the top of the phone. It worked just fine in earlier versions. 

Without checking the actual conversation list, I have no idea that a message came in. 

Does this help you replicate the issue? 
Kamakazi

**Comment by kistitan** [comment] 2017-11-23 18:56
@kamakazi414 

May I ask if it is a constant issue or something that happens sometimes?

**Comment by kamakazi414** [comment] 2017-11-23 19:20
It's a constant issue. However, yesterday I did get an alert for a notification of a friend request. An hour later, I got a private message that I did not get notified about. 
Curious I did some more investigation. I discovered that while my android settings had notifications turned on,  settings using my browser on my laptop, it was turned off. After I turned it on, I got my first alley on my android today. 
In my mind, these settings should act independently. I wasn't the notices on my phone but not my computer. 
I hope that helps. 
Rich.


http://richardverry.com
-------- Original message --------From: kistitan <notifications@github.com> Date: 11/23/17  1:56 PM  (GMT-05:00) To: fetlife/android <android@noreply.github.com> Cc: kamakazi414 <kamakazi414@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [fetlife/android] Not seeing when I have notifications (#371) 
@kamakazi414
May I ask if it is a constant issue or something that happens sometimes?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fetlife/android","title":"fetlife/android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fetlife/android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kistitan in #371: @kamakazi414 \r\n\r\nMay I ask if it is a constant issue or something that happens sometimes?"}],"action":{"name":"View Issue","url":"https://github.com/fetlife/android/issues/371#issuecomment-346683067"}}}

**Comment by kistitan** [comment] 2017-11-27 11:23
I can confirm that at website notification settings webnotifications include Android notifications too.
It is in our todo list to have a separate settings or at least make it more clear.

**Comment by kistitan** [comment] 2017-12-19 09:58
There were some recent improvement with notification visibility, also task added to improve the website settings to avoid confusion.

Closing this for now.

**Closed by kistitan** 2017-12-19 09:58 UTC
Labels: help wanted, Investigation
