### ISSUE TITLE
Notification Screen Blank

### ISSUE THREAD

**Issue by Subpixiepop** [fetlife/android#363] opened 2017-10-15 18:52 UTC
I am using 2.11.8 .. I get notification alerts, click them, app opens, but  the notification scren is blank

**Comment by kistitan** [comment] 2017-10-18 08:47
Hi @Subpixiepop 

May I ask what type of notifications were they?
Messages and Friend Request are displayed in the notifications screen but on the conversations/friend requests screen instead.

**Comment by Subpixiepop** [comment] 2017-10-18 12:02
HI! Notifications of like / name mentions.. Ill gwt an alert that someone
like a photo... I click it, it opens the app and the notification scren is
blank

I attached a screen shot....they have not been swiped deleted

**Comment by RedKitten13** [comment] 2017-10-19 22:59
I'm also using the app version 2.11.8 for my LG G3 using the latest Android software and receive notifications for Loves I get on my writings/posts, @mentions, et cetera, and - upon clicking said notifications heading - I am taken to the "Notifications" page within the app to view them but instead am faced with a blank page and the quick hint of "Swipe left to hide/delete a notification" but nothing else, so...

**Comment by kistitan** [comment] 2017-10-20 08:54
Thank you for the additional comments.
Still couldn't reproduce it on our test devices.
So I have to ask more patience from you.

Thank you

**Comment by Subpixiepop** [comment] 2017-10-20 20:50
Mine JUST worked!

**Comment by dsa157** [comment] 2017-10-21 16:20
same issue - v2.11.0 on a Verizon LG V10 running Android 7.0 
This only started happening when  upgraded to 2.11 recently

I get the notifications (mine are picture loves or comments) and then when I open the app is always opens in messages rather the notification screen. when I navigate to the notification screen, it is blank

**Comment by kistitan** [comment] 2017-10-24 22:38
Yes,

We found the reason for this for mentions and group comments.
(Likes should be still visible though).

Fix will be released probably tomorrow.

Thank you for your patience.

**Comment by kistitan** [comment] 2017-10-26 12:24
This issue should be solved in 2.11.13.

Please note, new message and friend request notifications are still handled in different screens so wont show up in the notifications screen.
Also please keep in mind notification screens collects in in-app notifications. It does not sync with web or email notifications. So just like if you delete en email, if you remove a notification in your app, it won't remove the notification at the website.

So you can still see empty notification screen after deletion while your website still show the previously (in the app) seen and deleted notification.

Notification display both in app and website is under redesign to reduce the several confusion user face with them.

Thank you for your help and understandings.

Please feel free to repoen this issue if it occured again.

**Closed by kistitan** 2017-10-26 12:24 UTC
Labels: bug, in progress, Investigation, Priority 2
