### ISSUE TITLE
All conversations not showing on tablet

### ISSUE THREAD

**Issue by halsteaw** [fetlife/android#113] opened 2016-07-20 02:50 UTC
On a large screen tablet, only the first 10 conversations are showing when there is space for more.

I suspect that it is not loading more because it is not detecting the scrolling it can't do.

**Comment by johnbaku** [comment] 2016-07-20 03:26
@halsteaw good catch.. thanks for submitting the bug!

**Comment by kistitan** [comment] 2016-07-21 17:23
@halsteaw 
Indeed thanks for reporting. As of now we are mainly focus on phone version, full tablet support is on our list, but of course we will try to provide at least the minimal functionality work also on large screens.
Fix will probably miss the next version, but try to solve it as soon as we can.

Thanks again

**Comment by kistitan** [comment] 2016-08-03 13:05
Hi there,

Sorry for the delay.
The issue is not fully solved but in order you to be able to use the app normally I added a temporary change that will cover also the situation you face.
It will be part of the next release: v1.4.

I reduce the priority now for the final solution that probably will come with the full tablet support.

Thank you for the patience

**Comment by kistitan** [comment] 2016-08-09 11:05
Workaround added in version 1.4.0.
Please reopen if you face to issue again.

(Final solution will be added together with full tablet support somewhere in the future)

**Closed by kistitan** 2016-08-09 11:05 UTC
Labels: bug, priority low, waiting for release
