### ISSUE TITLE
Usability: Settings screen has black text on a very dark background

### ISSUE THREAD

**Issue by Micconos** [fetlife/android#185] opened 2016-10-04 14:19 UTC
The "Settings" screen has black text on a very dark background which is very hard to read.

For a while I actually thought the "Settings" was empty (I've trying it out again from time to time, while going "Oh, still empty") :) Also, I think the colors could give users the impression that the "Settings" screen is disabled. 

All in all, the "Settings" screen should be consistent with the rest of the App, i.e. Dark/Black background and White text/font.

**Comment by kistitan** [comment] 2016-10-05 11:56
@Micconos 
Thanks a lot for reporting this issue.

The actually intention is to have white text with light grey subtext as it is how it does look on our test devices.
Can you please help us out with letting us know what device and Android O.S version do you use?

Thanks again

**Comment by reneklacan** [comment] 2016-10-05 12:31
@Micconos Maybe a screenshot would be nice as well. Thanks!

**Comment by Micconos** [comment] 2016-10-05 13:15
Samsung Galaxy Note 3 (N9005) running Android 5.1.1.

![screenshot_2016-10-05-15-12-19](https://cloud.githubusercontent.com/assets/17880697/19114457/59d73be4-8b0e-11e6-84e3-f8517fa11b92.png)

**Comment by reneklacan** [comment] 2016-10-05 13:30
wow, that's extremely unreadable 😮  ... now we see what you meant 😆

**Comment by kistitan** [comment] 2016-10-05 13:33
@Micconos
Thanks a lot.
I will take a look at it, and try to get a phone to reproduce.
Hopefully fix will be in next release.

Thank you again for letting us know about this issue.

**Comment by Micconos** [comment] 2016-10-05 15:32
FYI. I've also reproduced issue on a Samsung Galaxy Alpha (SM-G850F) with Android 5.0.2. :)

**Comment by johnbaku** [comment] 2016-10-05 15:40
That's a feature... not a bug! :-p

**Comment by FernandoMiguel** [comment] 2016-10-05 17:54
there should never be just a blank/black background. 
i have the same use case in the notifications .
a small icon in the background makes it easy to understand there is nothing else to load

**Comment by kistitan** [comment] 2016-10-20 08:39
Will be fixed in the upcoming major version...
Thank you for your patience.

**Comment by kistitan** [comment] 2016-12-01 09:27
Sorry for the delay. 
2.0.4 still does not contain the fix.
It is not forgotten, but turned out to be more complex that it seemed.

Some devices's OS work differently than the pure android OS and ignore the sytle setting for the Settings screen.
We will still try to solve this soon as it can be annoying.

Thank you for your understandings.

**Comment by kistitan** [comment] 2016-12-12 10:21
Postponed to next release as no comfortable solution found yet.

**Comment by kistitan** [comment] 2017-07-06 13:55
Had many issues with reproducing it.
Any help would be appreciated

**Comment by Micconos** [comment] 2017-07-06 14:04
@kistitan: I experienced the bug running a custom ROM (CyanogenMod) on my Galaxy Note 3.

I have since reverted to a stock Samsung ROM, and I can't reproduce the issue anymore.

**Comment by kistitan** [comment] 2017-10-19 06:51
Closing this issue as new other news about it.
Please reopen if it occured again.

**Closed by kistitan** 2017-10-19 06:51 UTC
Labels: bug, help wanted, open, Priority 2
