### ISSUE TITLE
While browsing on PC, notifications only come to Android

### ISSUE THREAD

**Issue by MaxiM-PL** [fetlife/android#293] opened 2017-04-03 14:22 UTC
And they never show up on the website under https://fetlife.com/ats, Noticed that 1-2 versions ago. It was fine before.

**Comment by kistitan** [comment] 2017-04-03 17:11
@reneklacan 

Do you know by heart what is our notification strategy?
Do we still intend to send notification to browser even if it is seen on Android?

**Comment by MaxiM-PL** [comment] 2017-04-03 18:17
Not sure what @reneklacan said since the post is gone, but just to be sure, the notifications were only received on my phone, but not viewed. I just saw them on my lockscreen and tried checking them out in my browser but there was nothing, so I had to view them on android and one by one find the replies manually via browser.

**Comment by reneklacan** [comment] 2017-04-06 14:17
Notifications should pretty much be send to every device where you enabled them.

@MaxiM-PL what do you see when you go to https://fetlife.com/settings/web_notifications? 

Is it something like this?

![](http://image.prntscr.com/image/bbc6dbcaa1c94bae90fc895b2643ec6c.png)

**Comment by MaxiM-PL** [comment] 2017-04-07 00:32
I'm not talking about web notifications. I'm talking about /ats. Once I receive then on mobile (without reading, just receiving) they are nowhere to be seen on the website. When I want to comfortably respond to a comment for instance, I need to then open the Android app, see where that comment was and then manually find it on PC. Not the most user friendly way - actually makes me want to uninstall the Android app.

**Comment by kistitan** [comment] 2017-04-11 16:03
Hi @MaxiM-PL ,

Thanks for your replay, for me the issue is still not 100% clear.
Maybe @reneklacan has some more insight on this.

Can you confirm that if the App is not available you receive the notifications via the website?
Receiving it in the App should not have any effect on receiving it in the website.

Thank you

**Comment by kistitan** [comment] 2017-06-01 08:32
Hi @MaxiM-PL 

As this issue has been not replicated for better overview I close this issue,
please feel free to reopen it if it occurs again.

Thank you

**Closed by kistitan** 2017-06-01 08:32 UTC
Labels: question

**Comment by MaxiM-PL** [comment] 2017-06-02 19:55
Happened again. This time I wasn't even near my PC web browser and Fetlife was not open for sure. Got a notification on my phone, but it's nowhere to be seen on the site. The specific kind of notification was a @mention in a comment under someone's photo. Hope that helps in pinpointing the cause of the issue. I *think* the last time I reported this it was a mention as well.
