### ISSUE TITLE
Notification inconsistencies

### ISSUE THREAD

**Issue by SqueekyST** [fetlife/android#552] opened 2019-05-06 14:50 UTC
# 🐛Bug Report

### Bug description 
App notifications had been working on this device. Last week I was traveling and set my notifications to be vanilla. This change worked as well. 
When I returned I disabled vanilla mode and ensured all notification types were enabled. This is when I noticed issues. 
At this point I started getting both standard and vanilla notifications for some events. The generic "you have private notifications waiting" did not take me to a notification (sorry, I forget if it took me to the inbox with no new messages or if it did nothing).
The notifications that said I have a message waiting did lead to the inbox where a message would be waiting. 
I uninstalled the app and reinstalled it and confirmed vanilla is off and all notifications are on. I have had nothing but vanilla notifications since then. I keep getting the generic notification with no new activity when I check. I've removed it from battery optimization, but I've continued getting these generic spam notifications.  

### Environment
FL 3.0.0
Android 7.0 (and can't be updated on this device)

**Comment by kistitan** [comment] 2019-05-07 11:54
Hi @SqueekyST ,

Thank you for reporting this issue.
We had a bug with clearing up notification stash, what has been fixed in 3.0.1

Would you please installing it and see if the issues has been gone?

Thanks a lot

**Comment by SqueekyST** [comment] 2019-05-08 02:46
I did the upgrade this morning. The false notifications are driving me nuts. They didn't start until after I got a legit message, but there have been half a dozen notifications since then without any new activity in FL.

**Comment by kistitan** [comment] 2019-05-08 07:59
@SqueekyST 

May I ask what kind of notifications are the ones that you receive plenty of them?

Just double checking if you enabled group notifications, they can be indeed overwhelming, depending on how many groups are you following (that is why this setting is turned off by default).
So how group notifications work:
- Every time you comment on a group discussion, you automatically get subscribed to that discussion
- If you are subscribed to a discussion, every time if someone comments on that discussion, you will get a notification in the App. It means if you commented many discussions in the past, and in some of them there is a heated discussion for example, than you will get indeed plenty of messages in a short amount of time.

This might not be the case in your situation, but it might be worth to double check.

So maybe as a first step you would like to:
- turn off only the group notifications in your app's settings, and see if the issue is solved
- If the issues is solved, than you can try to revisit your group that you are subscribed to and unsubscribe from as many as it makes sense to you, and check if the you start receiving less notifications

If nothing helps or the spamming notification are not group related, unfortunately as of now the only way to step forward is to see what is going on your device.
In that case would you mind helping us out with installing an extra logging version of the App?

In order to do so, please:

1. download the attached .zip file
2. rename the downloaded file from .zip to .apk
3. if it is not there already, move or copy the .apk file to your Android device
4. install the .apk file on your device, by locating it with your download or file browser app and executing it (please follow the on device instructions for the installation)
5. reproduce the issue, or wait until it is happening again
6. after it happened again, please open your side menu and select the new menu item: Share Logs
7. Please send the logs to krisztian@fetlife.com

+ If you can send us a screenshot of the spammed device notification area, that would be a great help too.

Thank you

[fetlife-3.0.2-beta.1+1557299758.zip](https://github.com/fetlife/android/files/3156199/fetlife-3.0.2-beta.1%2B1557299758.zip)

**Comment by kistitan** [comment] 2019-05-08 14:56
@SqueekyST 

In Anonymous mode, notifications are indeed anonymous, so they do not hold any information about what the notification was about. 
If you click on them they simple open the App, where you can see the inbox as this is the first screen in the App.

Group message notifications, just like message notification do not show app in the notification screen.
(There is a little overload here for the word "notification").
So indeed it can happen that there is a new group message, what will transform into an anonymous message in vanilla mode, and when you click on it, it simply takes you to the App, where you cannot see the source, until you browse your groups. 

This beahviour is not optimal, but vanilla mode is an old feature, where did target the most urgent requirement of privacy.

We already have a task on our todo list to come of with a different privacy feature.

Please let us know about, if disabled group discussion notification indeed will stop the spamming. 

We apologize for the inconveniences

**Comment by calvinwiii** [comment] 2019-05-13 17:19
With latest version. Phone toolbar and app icon both show a pending notification, however, within the app, the notification count was zero. Tracked it down and the notification was for a response to a post i had made in a group. The notifications did clear when i found and read the message

**Comment by kistitan** [comment] 2019-05-15 22:42
@calvinwiii 

First of all sorry for the late reply. 
Thanks for letting us know about this issue. 

Indeed as of now we do not have an in-app counter for group related notifications.
This situation is not ideal, and we are trying to find a solution for that. 
To get some hints about these notifications, you can check the Android Notifications screen within the App, that would reserve some of the incoming notifications or you can check directly the group related screens. 

We sorry for the inconveniences and we do hope we can find a solution for that sooner than later.

Dreamlite

**Comment by kistitan** [comment] 2019-05-22 09:49
Hey @calvinwiii m @SqueekyST ,

Please let me have a quick summary about the issues and their temporary solutions from above.
Issue reported by @SqueekyST :

- Notification screen do not display notification about new message in followed group discussions, counters are not populated after these type of notifications. (The reason for that is the number of these notification can be extremely high for some users, depending on how many group discussions (s)he commented.So it would spam the notification screen / counters)
- There is an option setting in the App to receive App notifications about new messages in followed group discussions. Please be aware, depending on how many discussions you follow (commented on already) the number of notifications can be intensive. 
- Opening App notifications about new messages in followed group discussions automatically redirects to the actual Group Discussion, unless Anonymous notifications Setting is turned on
- Anonymous notifications cannot redirect to the appropriate screen, they just open the App's main screen.
- Based on the points above, it can happen, an anonymous notification arrives, but after clicking on it there is no information about what was the actual notification about.
in that case, please use the App Notification's screen from the menu to get insight about previous App notifications.

**Closed** 2019-05-22 09:51 UTC
Labels: bug
