### ISSUE TITLE
Can not reach all notifications if they are grouped

### ISSUE THREAD

**Issue by 927589452** [fetlife/android#424] opened 2018-01-24 05:16 UTC
If the Notifications are grouped they are only available as one "link"

This is on a android 7.1.2
LineageOS 14.1

**Comment by 927589452** [comment] 2018-01-24 07:23
Eg only one of the notifications is opened

**Comment by FernandoMiguel** [comment] 2018-01-24 10:02
I agree.
this affects me a lot.
I receive notifications from several groups and it will only open the latest one, in the browser, not in the app :(

**Comment by kistitan** [comment] 2018-01-29 18:05
Hi @927589452, and @FernandoMiguel

Sorry for the late reply. In the meanwhile I could find the reason for this issue, please give me a bit of more time to figure out what is the best way to solve it.

Thank your for your patience.

**Comment by kistitan** [comment] 2018-02-08 11:44
There has been some improvement in latest release in this area so I close this fot now. Thank yiu

**Comment by FernandoMiguel** [comment] 2018-04-15 07:15
Why is this closed?
I'm still having grouped notifications that when I click take me to the group tab, but not the notification source itself, nor even the notification tab

**Comment by kistitan** [comment] 2018-04-22 10:26
@FernandoMiguel 

This is actually works as designed in case you have notifications from several different goups.
It is same as with messaging. If you have ntificatons from several discussion we cannot navigate you to all of them the same time.

The main issue here that for groups we cannot really have a new/unread indication at the moment. 

In the new version we will try to fgure out something better (like expandable grouped notifications)

**Comment by FernandoMiguel** [comment] 2018-04-22 10:48
Thanks for getting back to me on this.

Hopefully the new version allows better usage of the notification.

As it is now, it's really hard to use since clicking it will just open a
tab in the app with not the expected notification context.
I rather have it open in the notification tab than the group

--
Fernando Miguel

**Comment by kistitan** [comment] 2018-06-22 09:04
Reopened as an imporvement issue to have better grouped notifications

**Comment by kistitan** [comment] 2019-03-06 18:56
This issue should be solved by now.
Please note for older devices, with less convenient support for grouped notifications, and no individual opening, you might want to consider turn off the Notification Grouping in your App settings.

Thank you

**Closed by kistitan** 2019-03-06 18:56 UTC
Labels: Priority 3, feature, mark, waiting for release
