### ISSUE TITLE
Notification about latest version, while being on the latest version

### ISSUE THREAD

**Issue by ImperfMage** [fetlife/android#542] opened 2019-04-29 07:48 UTC
# 🐛Bug Report

### Bug description 
1. Still getting occasional Connection failed. Please try again later

2. Saying there is a "new fetlifePreiview version v.3.0.0-beta.1" even though it's already installed.

### Steps to reproduce

**Bug 1**
1. Go to the fetlife app as you normally would
2. Click on click on feed or whatever
3. Scroll down to anywhere
**Bug 2**
1. go to the app 
2. click on check update

### Expected behavior

**Bug 1**
It should not be showing Connection failed even though I have internet access
**Bug 2**
The system should recognize what version I have

### Screenshots

**Bug 1**
![Screenshot_20190429-021724](https://user-images.githubusercontent.com/28355914/56881282-8dfccd00-6a25-11e9-90c0-1f77bd08adf6.png)
**Bug 2**

[2019_04_29_02_26_54.zip](https://github.com/fetlife/android/files/3126306/2019_04_29_02_26_54.zip)

### Environment

 - Device: Google Pixel 3 xl
 - OS version: Android Version 9
 - App version. v.3.0.0-beta.1

**Comment by kistitan** [comment] 2019-04-29 10:17
@ImperfMage 

Thanks a ton for the bug report.

We can confirm that bug 2 is happening
We are going to fix in the next beta release, hopefully soon.

Bug 1 is a bit more tricky as we cannot reproduce it on our test devices, so we cannot see what is the actual reason for your connection issues.
But as it probably not directly related to the new release so I split into these two bugs into two different GitHub issues so we can track and focus on them separately. 

Please find the new report about bug 1 here:
https://github.com/fetlife/android/issues/543

**Comment by kistitan** [comment] 2019-05-07 11:57
This issue has been fixed in 3.0.0.
Please feel free to reopen this issue, if it was not the case.

Thank you

**Closed by kistitan** 2019-05-07 11:57 UTC
Labels: bug
