### ISSUE TITLE
New preview version downloads wrong apk

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#459] opened 2018-07-04 18:49 UTC
The notification for the new preview version 2.16.0 downloads the 2.15.5 apk. Tried it multiple times, including deleting all apk files from my download folder. No difference.

**Comment by FernandoMiguel** [comment] 2018-07-04 19:07
![screenshot_20180704-200625](https://user-images.githubusercontent.com/168366/42291785-d9b9b668-7fc5-11e8-958e-095b3e975f79.png)
Mine shows as 2.16

**Comment by flgnl** [comment] 2018-07-04 21:10
Well, after another couple of attempts I got the right version. The last time I went to the notifications list and started the download from there, instead of hitting check for updates. But I don't know whether that did the trick or something else.

**Comment by johnbaku** [comment] 2018-07-11 00:33
@kistitan ^^ has this been fixed?

**Comment by kistitan** [comment] 2018-07-11 06:40
Hi guys,

This is all very strange, as nothing has been changed in the notification and update mechanism. 
I also could not reproduce on my phone after several attempts. 
Let's wait for the next update and see if it still happening.
If it will I dig into deeper however at the moment I do no see any reason why this could happen.

Thank you

**Comment by kistitan** [comment] 2018-09-25 09:38
Hey guys,

Did anybody encounter this issue recently, or can I close it?

**Comment by flgnl** [comment] 2018-09-25 17:35
Haven't had this issue with later versions.

**Comment by kistitan** [comment] 2018-09-27 13:01
Thanks for letting us know.
Closing this issue for now, please feel free to reopen if it occurred again.

**Closed by kistitan** 2018-09-27 13:01 UTC
Labels: Investigation, Priority 3
