### ISSUE TITLE
No Notifications

### ISSUE THREAD

**Issue by Willow-Rose** [fetlife/android#313] opened 2017-06-07 16:46 UTC
I have the 2.8.1 version and I'm not getting any notifications. I've checked my settings and cleared the cache several times.

**Comment by kistitan** [comment] 2017-06-08 14:04
Hi @Willow-Rose 

Thank you for reporting this issue.
May I ask if you checked your settings both at the website and in the App?
Do you still get email notifications?

Thanks a lot and sorry for the inconveniences.

**Comment by kistitan** [comment] 2017-06-08 14:07
@SqueekyST

Can you please also check if you still receive email notifications?

Thank you

**Comment by Willow-Rose** [comment] 2017-06-08 14:11
@kistitan 

I have checked settings on both the website and app. I do still get email notifications.

**Comment by SqueekyST** [comment] 2017-06-08 14:23
I'll have to enable those since I've had email notifications turned off for years now.

**Comment by kistitan** [comment] 2017-06-08 14:28
I gave a few tries but could not reproduce the issue.
Would you mind installing a special build with extra logs so I can have more information about the issue you face?

**Comment by Willow-Rose** [comment] 2017-06-08 14:44
I wouldn't mind at all

**Comment by kistitan** [comment] 2017-06-08 15:11
Great, let me have some time to built up.
I will let you know.

Thank you.

**Comment by Willow-Rose** [comment] 2017-06-08 15:22
Ok. Thank you!

**Comment by SqueekyST** [comment] 2017-06-08 17:36
I'm now getting email notification but no app notifications for private messages.
@s still working fine.
I'll gladly install a tracker version.

**Comment by SqueekyST** [comment] 2017-06-08 17:44
I just went in to thank the people who messaged me and notice that the new icon is no longer clearing after reading and even replying. I haven't changed versions.

**Comment by SqueekyST** [comment] 2017-06-08 18:01
Reading the messages on the web cleared new from both locations.

**Comment by kistitan** [comment] 2017-06-09 07:16
Hi there,

As a wild guess before the tracking version.
Would you mind go to App settings and turn off and on again the notifications for message notifications and than try again if it works?

Thank you

**Comment by kistitan** [comment] 2017-06-09 10:54
Hi there,

Here is the logging version.
- Please unpack it
- Install the apk file (for example copying to your phone, than opening with a file browser)
- Start the app, log in, log out, etc - as you usually do
- Make sure somebody sends you a message. (You can send to each other :) or just let me know and I will)
- Than wait a bit, about 30-60 seconds
- Repeat this a few times if you can
- Open the app and open the menu
- Select: Send logs (at the bottom)

Thank you!


[fetlife-2.8.4.zip](https://github.com/fetlife/android/files/1063798/fetlife-2.8.4.zip)

**Comment by SqueekyST** [comment] 2017-06-09 12:14
The last test didn't work.
I have no issues downloading the files: they go to my SD card. But, I don't have room to install a zip extractor. Is there another way to get the apk?

**Comment by Willow-Rose** [comment] 2017-06-09 12:24
Last test didn't work for me either. My phone says it can't open the file.

**Comment by CristitheTog** [comment] 2017-06-09 14:20
I will install the 2.8.4 version to help you test things. I am running the app on a Vonino Sirius QS and I have the same problem, not receiving notifications. Everything worked fine until the update. Maybe there's a bug with older OS's.

**Comment by CristitheTog** [comment] 2017-06-09 14:27
I sent a message on my account from a different one - created a blank one - and loved a lot of photos from it. Than I've sent you the logs. Hope it helps in fixing the bugs :-)

**Comment by kistitan** [comment] 2017-06-09 18:59
Hi there,

Can you maybe check this link for the file?
https://drive.google.com/open?id=0B2T3HBhIHxxXNHphaUF1bmJHeW8

Thank you

**Comment by kistitan** [comment] 2017-06-09 19:19
@CristitheTog 

Thanks a log for your help.
From you logs I can see the the push messages arrive to your phones, all settings are fine, and actually the Android OS API to display the notification is supposed to be called... But appearantly it does not work.

I will try to look after what can be the reason, int the meanwhile can you all rather use this version 
(I added a bit more logging to these)

https://drive.google.com/open?id=0B2T3HBhIHxxXRGh4bkNrLXpkVXM

Thank you all!

**Comment by SqueekyST** [comment] 2017-06-10 02:03
I've got it installed now, just need some messages. I'm SqueekySexToy if anyone here wants to message.

**Comment by Willow-Rose** [comment] 2017-06-10 02:05
Sent in my logs. Had someone message me twice, comment twice, and love 2 of my pictures. I never got a notification for any of them.

**Comment by Willow-Rose** [comment] 2017-06-10 02:08
@SqueekyST I just sent you a message

**Comment by SqueekyST** [comment] 2017-06-10 03:07
I just sent my logs. It includes messaging with willow-rose and someone else. No notifications.
No other activity since I wasn't having issues with those.

**Comment by SqueekyST** [comment] 2017-06-10 03:08
I just sent my logs. It includes messaging with willow-rose and someone else. No notifications.
No other activity since I wasn't having issues with those.

**Comment by CristitheTog** [comment] 2017-06-10 07:08
@kistitan, I sent a request for access at the Google Doc. 

Have a great day

**Comment by CristitheTog** [comment] 2017-06-10 08:54
I did another test. I installed the 2.8.7 version on a Samsung Galaxy Tab running Android 5.1.1 and the notifications came instantly. The problems with the notifications not popping up are on the Vonino Tablet Sirius_QS which is running Android 4.4.2, it's an older type of OS. As I am typing this message I received notifications from YouTube and Gmail on the Vonino.

**Comment by kistitan** [comment] 2017-06-11 09:02
Hi there,

I appologize it takes that long, but as it works for most of the users and the notification is lost at the call of an OS API it is hard to see what goes wrong.
I shared a test apk with you to narrow down, the issue.
If you are still not tired, could you please confirm it works without any issues?

Thank you

**Comment by SqueekyST** [comment] 2017-06-11 12:32
Your notification tester worked for me: triggered a notification and directed to a dev page.

**Comment by CristitheTog** [comment] 2017-06-11 12:37
It worked for me too.

**Comment by Willow-Rose** [comment] 2017-06-11 14:40
Worked for me too

**Comment by kistitan** [comment] 2017-06-12 15:31
Thank you!

Now I have to find the steps in between :)
New version has been shared. 2.8.8
Can you please receive message and let me know if you see any notification if yes, can you please let me know which ones?

(There are 5 different notification is requested by the OS, hopefully at least one of them will be visible by you)

Thanks

**Comment by Willow-Rose** [comment] 2017-06-12 16:12
I'm getting notifications for messages but still not for comments or loves. For messages I'm getting both V1 and V2.

**Comment by kistitan** [comment] 2017-06-12 16:16
yes, i added tests only for messages. So no v3 and v4, thank you!

**Comment by kistitan** [comment] 2017-06-12 20:47
Based on the last test and not displayed notification of v3 and v4 and made a new version.
Could you please give a try?

Thank you

https://drive.google.com/open?id=0B2T3HBhIHxxXOTFaRzhaNnBWNXc

**Comment by SqueekyST** [comment] 2017-06-13 02:23
No message notifications for 2.8.8 or 2.8.9

**Comment by Willow-Rose** [comment] 2017-06-13 04:48
I got a notification for the message I received. Didn't say which one or combination of ones it was.

**Comment by kistitan** [comment] 2017-06-13 06:14
@Willow-Rose 
2.8.9 does not contain variations any more. It is a the planned fix version.
Can you please play around with it and confirm that now you receive notifications?

@SqueekyST 
Can you confirm that you don't receive notification, not even with 2.8.8 at all?
There are 5 different notifications are set up in that version and one is exactly the same as it was in the sample app that worked for you. If you don't receive notifications at all I am afraid I really cannot do much without having your phone physically here :(

**Comment by CristitheTog** [comment] 2017-06-13 09:12
Message notification - Check
Writing love notification - Check
Photo love notification - Check
Friend request notification - Check
Can not check video notifications 

There is a small delay in receiving the notifications, but, IT WORKS and that is great. Thank you for having the patience to try and solve the minor bugs.

**Comment by CristitheTog** [comment] 2017-06-13 09:13
Not just trying, but, solving them.

**Comment by SqueekyST** [comment] 2017-06-13 09:43
If @cristithetog experienced delays, maybe I checked my messages too fast? I've continued getting all the other notifications and I know my original issue was not timing.
I'll go back a version and see what I get.

**Comment by Willow-Rose** [comment] 2017-06-13 12:50
I get all notifications. I'm also experiencing the delay, but also totally fine with it since I'm now getting the notifications. Thank you so much for your hard work!

**Comment by kistitan** [comment] 2017-06-19 16:48
Perfect!

So I am closing this issue as the release went live!

Thank you for the patience for all of you!

**Comment by SqueekyST** [comment] 2017-06-19 22:49
@kistitan
Because we never came up with a fix for my device I went back and tried 2 older versions that had been working for all notifications, but they are also doing all notifications except messages. 
If I want to start again from scratch, how do I ensure any corrupt components are fully removed. Is a basic uninstall enough?

**Comment by kistitan** [comment] 2017-07-10 17:04
@SqueekyST 

Sorry for the late answer.
I am really sorry that notification does not work for your device.
Uninstall should be enough for sure.
Did you try 2.9.1 btw?

**Comment by SqueekyST** [comment] 2017-07-10 17:43
I'm on 2.9.0 with all notifications except messages. I did clear everything and reinstall.

**Comment by kistitan** [comment] 2017-07-10 18:35
You mean you receive notifications except for messages?

**Comment by SqueekyST** [comment] 2017-07-10 19:30
Right. I get notified of likes, friend requests, follows, comments on threads I started and new posts in my groups.
But never when I get a message in my inbox.

**Comment by kistitan** [comment] 2017-07-10 19:41
That's very weird.
I will reopen the issue again than.
Sorry about that.

**Comment by SqueekyST** [comment] 2017-07-18 12:42
I figured it out! 
I had my web notifications for messages turned off. We'd only checked the email notifications.

Now that we figured it out, can we actually make it work properly? Privacy needs for the computer should not be the defining factor for the app. My computer is hooked up to the family TV. My app is on a personal cell phone.

**Comment by kistitan** [comment] 2017-07-20 13:20
Hi @SqueekyST ,

Thank you for your investigation!
Let us talk about a bit internally to see what support we can have.

Thank you

**Comment by kistitan** [comment] 2017-12-19 10:19
We have a separate task for changes at the website to improve the working of notification settings.
I close this issue here due to duplication.

Thanks again

**Closed by kistitan** 2017-12-19 10:19 UTC
Labels: enhancement, Priority 3, waiting for backend change
