### ISSUE TITLE
Vanilla FL app shows username in notification

### ISSUE THREAD

**Issue by xCette** [fetlife/android#218] opened 2016-11-24 17:21 UTC
When using the vanilla version of the application friend request show up with the username in the notification. This is fine mostly except when you have very explicit words in the notification it can be easy to pull down your notification bar and not know what is going to be shown. This is a problem when others are looking over your shoulder obviously

**Comment by kistitan** [comment] 2016-11-24 20:09
@xCette 

Thank you for reporting this issue.
In Vanilla version App notifications are intended to be anonymous by default without containing any explicit content.
Can you please check your App settings if the anonymous notification settings are turned on for you?
If it is not please turn on now. If it is, than please turn it off and on again.

In the meanwhile of course we also investigate this issue from our side and get back to you when we see what makes it work differently as it was intended.

Thanks again

**Comment by kistitan** [comment] 2017-01-18 12:45
Hi there,

I tested it with our new merged version (2.2.1 and up) and this issue seems to be obsolete.
Please feel free to reopen in case if it occurd with newest versions too.

Thank you

**Closed by kistitan** 2017-01-18 12:45 UTC
Labels: bug, in progress
