### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by conway21** [fetlife/android#333] opened 2017-07-26 04:43 UTC
This happens nonstop for 5-10 minutes at a time when loading. The error message reads: CONNECTION FAILED. PLEASE TRY AGAIN.  It is making me want to just go back to using Google Chrome for fetlife. I know it's not my WiFi or Mobile Data because it does it any phone I try it on. Please fix this quick!

**Comment by kistitan** [comment] 2017-07-26 17:16
hi @conway21 

Thank you for reporting this issue.
We are sorry that you are facing problems.

We could not reproduce the issue on any or our test devices, so we would appreciate if you could give us some hint where in the App do you actually encounter the issue.

Thank you

**Comment by mocafet** [comment] 2017-08-07 18:01
Hey Kistitan, 

I too am seeing the same on my s7 edge.  Whenever I try to really load any screen I get the error message at the bottom.  When I try to send messages they do not send but instead show red. 

I have found if most prevalent when viewing someone's profile / trying to look at the pictures/ activity tab and most definitely messages. 

Hope this shines a bit more light on the issue!

**Comment by kistitan** [comment] 2017-08-09 07:51
Hi @mocafet,

Unfortunately we still could not reproduce the issue. So it is hard to see what is going on from here.
May I ask if you face the same issue in all network? Or is it related to some specific wifi/mobile network?
Some networks might block adult websites like FetLife and also for some mobile networks you have to explicitly allow it.

If this is not the case all I can do is to add some extra logs in the next version and analyize them later.

Thank you for your help

**Comment by mocafet** [comment] 2017-08-13 14:32
Hey kistitan,

I have checked on multiple networks. My own personal wifi which has no restrictions,  friends wifi network, my mobile carrier network and other mobile carriers. 

I was going to ask if there were any logs I can try to pull for you. Not sure if you guys have something similar to Charles proxy setup. 

I have not been able to find an exact reason as to why it happens, there are times it works ok (not great but ok) and other times it's completely unusable.

**Comment by kistitan** [comment] 2017-08-15 06:44
Hi @mocafet ,

Thanks a lot for your investigation.

We use 'retrofit" as a communication layer what is widely used and pretty stable networking library.
We give start the request and we display this error message in theory only if retrofit reports us that communication fails.
If the requests are incorrect it should fail all the time. 
If our API is unstable this issue should be very frequent in All the App instances.
As of now I cannot see any reason why it is happening :(
And unfortunately in current version we indeed do not have any further logs available.

We are working at this moment on supporting groups in the App.
It is in a bit delay because some API changes needed, but I will make sure it will contain additional logs in the networking layer so we can have better overview what is going on.

Thank you

**Comment by mocafet** [comment] 2017-08-27 01:27
Hey Kistitan, 

I haven't seem to of had any issues since I updated to the new preview version.  Simultaneously with that, I did look into the connectivity on my side. 

I did notice a potential issue with some IPv6 connectivity to certain websites. Although this does not explain the issue with the mobile data. 

The IPv6 issue was not on the fetlife side, and I would be happy to pass along further details preferably not publicly though. 

I can send you a message through fet if you like.

**Comment by kistitan** [comment] 2017-08-28 07:19
Hi @mocafet 

Thank you for your update.
In the meanwhile I discussed this case with my colleagues and some connection problem can be caused also by our current loadbalancer. We recognize some latencies also at the website.
As you might know we recently moved our backend to cloud services and the moving processed is till in progress. We have to fine tune several things.
So I would like to ask for your patience if it happens again.
We are working in it.

Thank you for your understandings

**Comment by PhilosophersSage** [comment] 2017-11-29 01:34
I too have been getting communication errors. Using version 2.12.19 on a Google pixel running Android 8.0. This often happens when viewing a profile or group and only lasts a few minutes. It's only certain profiles that have the problem, there are other profiles/groups that I can visit with no problems but when I go back to the problem one it persists. If I force close the app and restart there are no longer problems or I can click the view button and visit the profile/group through my browser.

**Comment by kistitan** [comment] 2017-11-29 16:46
Hi @PhilosophersSage ,

Thank you for your message.
Connection problems for profiles usually occur if the given user is not exist any more or archived or blocked you, but the profile itself was not removed yet from  the cache of the app.
Can you please confirm if this is the case in your time too?

**Comment by PhilosophersSage** [comment] 2017-11-29 22:24
Hay @kistitan, this is not the case. Please read the last sentence of my initial trouble report.
"If I force close the app and restart there are no longer problems or I can click the view button and visit the profile/group through my browser."
I will attempt to take a bug report and send it to you, hopefully that will provide more information.

**Comment by kistitan** [comment] 2017-11-30 13:01
@PhilosophersSage 

I apologize. I indeed your first comment was clear. Sorry for that.

We are a bit puzzled by this issue as the earlier loadbalancer issue is not there any more.

On client side we have some logs that indicated some users have time out issue trying to reach our API.
as the time out is already very high in general it could mean that either the device has no reliable internet connection or the API is down/busy (there are some other options, like mobile provider blocking etc, but they seem to be unlikely in these cases). 

But based on your feedback issues occurs also with stable internet connection and we also do not see any sign of API outage or slow response times.

It is also very strange that connection works again after force closing the App...

We will figure out a solution, just at this moment we are in a bit of darkness.

Thank you for your patience and support.

**Comment by kistitan** [comment] 2017-11-30 13:20
A great help could be from all of you if next time the issue occurs (especially the one that does not go away without app restart), you could note down and send me:
- the exact time when it occurs
- your device type
- your os version
- your app version

Any help is more than appreciated. Thank you!

**Comment by kistitan** [comment] 2017-12-19 10:17
Unfortunately we still cannot reproduce it from our side.
Please feel free to provide us the information as stated above so we can process it further.

Thanks a lot for your understandings and help.

**Comment by PhilosophersSage** [comment] 2017-12-19 12:35
I have not received any of the connection issues since updating from 2.12.19, but then I have not been doing as much browsing as I had before.

**Comment by kistitan** [comment] 2018-06-22 08:55
Closing this for now, please reopen if it occured again.

**Closed by kistitan** 2018-06-22 08:55 UTC
Labels: Investigation, Priority 3, help wanted
