### ISSUE TITLE
Search - profile view error

### ISSUE THREAD

**Issue by bradfordev** [fetlife/android#530] opened 2019-03-22 08:39 UTC
Recent changes are causing a major bug after searching a profile and viewing it. The profile is displayed as a web page and not as a mobile app compatible page. Please revert back to previous version of search

**Comment by bradfordev** [comment] 2019-03-25 07:06
Please provide a compiled fetlife apk v2.21.2. 🙏 Using the last version is a nightmare 😞

**Comment by kistitan** [comment] 2019-03-25 14:09
@bradfordev 

Thank you for reporting this issue.

I am afraid we v2.21.2 would not help in this case as the issue you are facing might be a result of a server side change, what we are trying to adapt to in the App.
What means 2.21.2 would cause probably even more annoying issues (if not at the moment, than in few days, as the server change is in progress).

So I am afraid the best shot is to find the reason why are you facing this issues, while it does not happen on our test devices.

Would you mind writing me the detailed steps of reproduction in private via email: krisztian@fetlife.com?
Including search term, and the exact profile you are trying to open and causes the issue.

Can you maybe also let us know your device type and Android version?

Thanks a lot for your help

**Comment by kistitan** [comment] 2019-04-16 09:08
Closing this issue for now.

Please feel free to reopen this issue if it occurred again.

thank you

**Closed by kistitan** 2019-04-16 09:08 UTC
Labels: bug
