### ISSUE TITLE
Formatted Links : Markdown support

### ISSUE THREAD

**Issue by JimKnoxx** [fetlife/android#361] opened 2017-10-11 12:07 UTC
Hello
I found a bug with links:
When using the formatting tool to insert a link as a word e.g. [Test][www.google.com] the website will show it correctly as a clickable word, but the app writes the full "[Test][www.google.com]" with clickable hyperlink.

**Comment by kistitan** [comment] 2017-10-11 13:59
Hi @JimKnoxx ,

Unfortunately it is not a bug, but a missing feature.
App does not support the same formatting as the website, due to the different platform standards.
But we indeed see that in some cases it can be annoying, so we will see what we can do about it.

Thank you for letting us know about

**Comment by Two-Finger** [comment] 2017-10-23 16:32
This is a different, but related issue:
![link](https://user-images.githubusercontent.com/3533666/31900024-d43bafba-b825-11e7-946b-36cdada49eb5.png)
The closing parenthesis that is supposed to be Markdown, along with the text following it (the period, here) , is interpreted as part of the URL. Tapping it leads to a 404.
On the website everything is fine.
I've seen links in other discussions that work okay, though.
This is the comment with the problem: https://fetlife.com/groups/68465/group_posts/9578831#group_comment_101471899
Here's another one that works okay: https://fetlife.com/groups/1507/group_posts/10123962#group_comment_96833960

**Comment by kistitan** [comment] 2018-10-29 10:16
Solution for this issue had been released than revoked as the library was used, caused performance issues.

Also we are now working on replacing the screens with webview based screens in the near future that will have the same content as the website, so this support will be automaticaly there.

Closing this for now

**Closed by kistitan** 2018-10-29 10:16 UTC
Labels: Priority 2, Priority 3, bug, feature, waiting for release
