### ISSUE TITLE
High Battery Drain

### ISSUE THREAD

**Issue by navimeara** [fetlife/android#184] opened 2016-10-03 20:32 UTC
Have a Samsung Alpha newest android software. After installing the fetlife app was draining my battery rapidly sow I had to remove fetlife from my phone

**Comment by kistitan** [comment] 2016-10-03 21:54
Hi @navimeara

Thank you for reporting this issue.
This is extremely strange as you can get report of the battery consumption of your app by the Android OS, and even on our test devices where we use the app a lot FetLife App I'd not even displayed in the list of Apps consume battery.

FetLife App doesn't have any background process running when you don't you it actively or when you receive a message.
Furthermore it should significantly consume less battery than opening FetLife from a browser.

So we really suggest to give another try, install it again and with normal phone usage monitor the list of the application under your OS settings 
> battery

If the FetLife all continuously displayed there please send us a screenshot so we can see how serious the issue is,
If it is not there you can safely keep using the app.

Thanks again!

**Comment by kistitan** [comment] 2016-10-05 11:57
I close this issue now as there is no other sign of high battery usage.
Please feel free to reopen it any time if the OS reports high battery usage.

Thanks a lot!

**Closed by kistitan** 2016-10-05 11:57 UTC
Labels: question

**Comment by navimeara** [comment] 2016-10-05 23:38
Hi
Thxs for closing. Did install again seems to work fine now

Op 5 okt. 2016 13:57 schreef "kistitan" <notifications@github.com>:
