### ISSUE TITLE
Server could not be reached error.

### ISSUE THREAD

**Issue by Coneyisland39** [fetlife/android#344] opened 2017-09-07 23:12 UTC
Still getting error message saying "Server could not be reached. Please check you internet connection." I have tried different wifi networks & I am using the 2.10.0 update.
![screenshot_2017-09-07-19-07-48](https://user-images.githubusercontent.com/31748756/30189185-777a21a6-9400-11e7-81b7-7c8dcab1a2f2.png)
![screenshot_2017-09-07-19-07-35](https://user-images.githubusercontent.com/31748756/30189187-77a4708c-9400-11e7-8add-7aad17adfdec.png)

**Comment by kistitan** [comment] 2017-09-08 06:51
Hi @Coneyisland39

We cannot reproduce the issue on 2.10.0.
Can you please confirm its still happening?

Thank you

**Comment by mocafet** [comment] 2017-09-08 14:46
I am also not seeing this happen yet so far.   Are you seeing the issue when not routing through VPN as well?

Are there any commonalities to the networks? All traffic through same VPN? Etc

**Comment by wolfxlittlered** [comment] 2017-09-08 15:05
I have experienced this v2.10.0 on mobile data network (Straighttalk) but the issue was resolved by connecting to WiFi, stopping the app, clear cache and data in settings/apps/fetlife, sign in app, turn off WiFi. 

It is quite a few steps but so far no connectivity issue since.

**Comment by Coneyisland39** [comment] 2017-09-11 20:30
Hi @kistitan @mocafet 

It is sporadicsporadic. Get it often throughout the day. Just took this screenshot.
![screenshot_2017-09-11-16-25-01](https://user-images.githubusercontent.com/31748756/30295356-5047e44a-970e-11e7-844e-501e6673c9d5.png)

**Comment by kistitan** [comment] 2017-09-12 11:47
@reneklacan 

Do you happen to see any reason from server side for sporadic connection issue?

Thank you!

**Comment by FernandoMiguel** [comment] 2017-09-12 12:44
I can confirm it's happening to me too in the latest version
every so often, mid sending a message it will say it cant reach the server

**Comment by awesomeff** [comment] 2017-09-13 18:15
I can confirm server connection errors

**Comment by jidanni** [comment] 2017-09-19 11:13
Me too.

**Comment by kistitan** [comment] 2017-09-19 11:31
Hi guys,

We are investigating this, but do be honest we are a bit puzzled.
We don't see much connection issue at our server side logs, so it means probably the device could not even reach the server API.
On the other hand in the latest version there was no changes aside changing the server certificate.
Based on that we suspect it can have something to do with that, but if the certificate was not correct you could not connect at all...
We don't see clear on this issue, so we are going to add some extra logs in the upcoming versions to see what's going on.

Thank you or your understandings and patience

**Comment by jidanni** [comment] 2017-09-19 14:50
Okay maybe it had something to do with 
 https://github.com/fetlife/android/issues/347 . After I updated the app and lived in again everything finally worked.

**Comment by kistitan** [comment] 2017-10-19 07:24
Merging to 
https://github.com/fetlife/android/issues/333

**Closed by kistitan** 2017-10-19 07:24 UTC
Labels: in progress, Investigation, Priority 3
