### ISSUE TITLE
Group comment notifications crash the app. 

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#507] opened 2018-11-30 16:47 UTC
Preview version 2.19.0

When I go to the app notifications and tap on a group comment notification, the app crashes.

**Comment by kistitan** [comment] 2018-12-05 09:34
@flgnl 

Thanks for reporting this issue.
We are investigating it.

**Comment by flgnl** [comment] 2018-12-05 10:19
Hitting the plus icon in the notifications screen (no idea why that is there) also crashes the app.

**Comment by DevN1mr0d** [comment] 2018-12-05 11:57
I will check later if I can reproduce on my device and that I can find something in logs

**Comment by DevN1mr0d** [comment] 2018-12-05 23:16
I could not reproduce it.

**Comment by flgnl** [comment] 2018-12-06 05:54
It had been fixed in 2.19.2

**Comment by kistitan** [comment] 2018-12-06 11:31
Indeed it should be fixed in 2.19.2

**Closed by kistitan** 2018-12-06 11:31 UTC
Labels: Priority 1, bug
