### ISSUE TITLE
Feed data  connection failed error & lack of content.  

### ISSUE THREAD

**Issue by zenwarrior88** [fetlife/android#294] opened 2017-04-03 15:07 UTC
Not getting all the feed. Only appx 45 minutes.  On PC over 3 hours  (I got tired of scrolling). Also getting connection failed error when scrolling to the bottom lf the feed with the app. 2.6.15.

**Comment by kistitan** [comment] 2017-04-03 17:10
hi @zenwarrior88 

I do not see any app related issue here.
Do you still face the issue?
Did you try to log out/in again?

Thank you

**Comment by zenwarrior88** [comment] 2017-04-03 19:12
I'll log out and try again

**Comment by zenwarrior88** [comment] 2017-04-04 04:15
I got almost 3:45 hours of feed before the connection failed error returned.  :)

**Comment by kistitan** [comment] 2017-04-04 14:26
Hi @zenwarrior88 ,

I am in a bit in dark with this, as I cannot reproduce the issue.
Would you mind giving a try to reinstall the App to see if it makes any difference?

Thanks a lot for your patience

**Comment by zenwarrior88** [comment] 2017-04-04 15:49
Uninstalled App. Installed 2.5.8 then updated to current preview version 2.6.15. Logged in. Cleared app data. Browsed the feed  pretty good till about 5 hours in the past.  Then the app crashed.  But not the same message.  So maybe it's ok. more testing forthcoming. :)

**Comment by kistitan** [comment] 2017-04-06 05:39
@zenwarrior88 

Ia ma happy it is working now. 
We are investigate the crashes that we see separate to this thread, so let me close this issue now.
Feel free to reopen it it occured again.

**Closed by kistitan** 2017-04-06 05:39 UTC
