### ISSUE TITLE
Events not showing up

### ISSUE THREAD

**Issue by threetwoonezero** [fetlife/android#432] opened 2018-02-23 23:47 UTC
Hi -

It seems a lot of events are not showing up on the map.  Some of these are probably because the address is "PM for", but others like this one ( https://fetlife.com/events/635453 ) don't seem to show up either.  Can events with no/invalid address just be placed on each city's center?

On this subject is there plans to get a chronological events list like on the website, or to get notified when new events are created?

**Comment by kistitan** [comment] 2018-02-24 21:05
Hi @threetwoonezero ,

Thank you for opening this issue.
It is a bit tricky. At the first version we used to have those events with not properly set address on the map, but later we decided to remove them as they cause some confusion.
Adding events just to the city center can cause several issues. 
If there are plenty of them adding all of them to one place cause a lots of event the exact same place what can cause issues hard to solve both performance wise and ergonomically.
Other issue is that they really can mislead users who start for example the navigation via the map and can end up in a totally different place.
So actually one of the best things we can do is to encourage users to add proper locations.

The reason why not every location shows up on the map, with visible address is that as of now the location is calculated only by the address field, what is required to be a full address, unless location API won't find the exact location. 
Some users rather provide the location separately what still make it visible, but not found by our API.
There is already an open issue for that at server side to look for other fields to for the full location.


Aside of the event Map you can always search manually for an event (search for events is accessible by sliding to the right at the header area of the Map), for example adding the location that you are interested in as a search term. 
The cronological order is not yet on our todo list, an exact search can probably give more accurate result for the user and can save resource not looking for a full list with less important events for the user, but it still should be taken into consideration as a possible improvement.

**Comment by toxalot** [comment] 2018-04-29 10:53
@kistitan wrote:

> Aside of the event Map you can always search manually for an event

This presents a problem for common city names. I tried a search for London and the results included locations all over the world. In most cases, you can't easily tell if it's even in the same country unless you click on the event. I tried searching for London, Ontario and that gave me ten results. I tried removing the comma between city and province and that gave four results. Two of the four were in the other list and two weren't. Searching for London, Ontario on the website, with or without the comma, gives 34 results. Using Places on the website shows that there are 31 events in London, Ontario.

**Comment by kistitan** [comment] 2018-06-22 08:17
Hi again,

This is more an improvement for our core search, but it should be driving from the Android side so I keep this open here.

Improvements should be considered to have more event on the Map;
1. As some users add the exact location splited in several fields during event creation, the exact location is not taken into consideration. That should be improved from the search engine side
2. We should find a way to display events that are generally point to a city without a specific address. We have to make sure it is not misleading for the users who might believe they are actually happening at the place that is marked on the Map.

**Comment by adventure17** [comment] 2018-07-04 04:02
The issue seems a lot broader than you might think.   I would estimate more than 1/2 the events in Toronto that show up as "near me" in the browser don't show up in the Android app, so the Events section of the app is nearly useless as present.  While the address may not be perfect, the browser link has no problem resoling it on a map in many cases - e.g. https://fetlife.com/events/667552 for example.   Even providing the results similar to the chronological "near me" list available from the browser would be a useful addition.

**Comment by kistitan** [comment] 2018-07-04 08:16
Dear @adventure17,

The mentioned event is not displayed on the map is the end date is in the past. 
To make the event maps as smooth as it possible we filter out any events that is already finished.

Do you happen to know any other example of not showing event, where the event is still not finished?
Can you maybe help us out with a use case when you would like to see an event from the past in the event map?

Thanks a lot for your help

**Comment by adventure17** [comment] 2018-07-04 15:37
I understand why you don't want to show past events on the map and, to be clear, that event was current last night, but obviously past us now.   How about this event on July 13th. https://fetlife.com/events/681600 .  Another one on July 14  ( might be thrown off by "second floor" reference), but still Google maps finds it fine on the browser fetlife, but not on the Android app.  https://fetlife.com/events/677152 .   It just seems very hit and miss/buggy, so it seems like a higher priority than 3.

**Comment by kistitan** [comment] 2018-07-11 17:40
@adventure17 ,

Thanks a lot for finding those events for us.
I can confirm we do not receive those events from the API to the App.
I reported to our API developers.
Will let you know as soon as it is fixed.

Thank you again!

**Comment by adventure17** [comment] 2018-07-11 18:09
No problem.  Happy to help.

And just to add to the thinking on events that don't have a specific address, but are tagged to a specific city/town.   Perhaps those items shouldn't appear as a pin on the map (as you noti above that was confusing), but they could appear in a floating menu bar or button.   Alternatively, it would be useful to just add another page, in addition to the "My events" and "search" pages, have a "Near me" list of events that has the same list as one gets on the browser under "Near me".   Hope that helps.

**Comment by markusb** [comment] 2018-09-25 11:03
Just joining here, because my bug #481 was closed as duplicate of this.

But my problem is different: I added a couple of events with a working address and they did show up ok. Then the address of the event changed and I changed the address of the event. The new address works fine too. But the app still shows the event at the old address, despite the change, even months later.

**Comment by kistitan** [comment] 2018-09-27 13:09
@markusb 

It is my fault, I indeed misunderstood your description.
I am really sorry for that.

I reopen your original issue.

**Comment by kistitan** [comment] 2018-10-31 09:54
Small update:

Investigated and turned out to be a backend issue.
New internal backend bug card has been opened for this issue.

Keeping this issue open here only to notify the user in case of the backend bug has been fixed.

**Comment by kistitan** [comment] 2018-10-31 10:00
Merging into: https://github.com/fetlife/android/issues/497

**Closed by kistitan** 2018-10-31 10:00 UTC
Labels: Priority 3, feature
