### ISSUE TITLE
No line breaks in group posts 

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#473] opened 2018-07-20 07:52 UTC
All line breaks seem to be missing in group posts. Saves space, but makes them harder to read. Especially, it makes it impossible to see where a quote ends and regular text continues.

2.16.4

**Comment by FernandoMiguel** [comment] 2018-07-20 08:27
bios are also broken

**Comment by FernandoMiguel** [comment] 2018-07-20 08:28
sounds like dupe of 
https://github.com/fetlife/android/issues/472

**Comment by flgnl** [comment] 2018-07-20 09:51
Or related anyway.

**Comment by flgnl** [comment] 2018-07-20 19:42
Fixed in the new version I see!

**Comment by kistitan** [comment] 2018-08-07 09:25
Hey there,
This one should be fixed in 2.16.7.

Please reopen it if you see the issue again.

Thank you!

**Closed by kistitan** 2018-08-07 09:25 UTC
