### ISSUE TITLE
App ignores password settings

### ISSUE THREAD

**Issue by Seelenoede** [fetlife/android#169] opened 2016-09-03 19:54 UTC
Sometimes if I open the app, it asks me for my password. Although I tell it to not do so (I unmark the option to ask me any time I open the app).

I have not tested it but I think it always happens if I open the app by tapping on a Fetlife notification.

**Comment by kistitan** [comment] 2016-09-03 20:26
Hi Seelenoede,

Thanks for reporting.
This issue indeed popped up with 1.6.2
Did you try with 1.6.3?
Does issue still exist?

Thanks again

**Comment by Seelenoede** [comment] 2016-09-03 20:56
Looks like I missed that update. I updated and will inform you if I have this error again

**Comment by Seelenoede** [comment] 2016-09-03 21:58
I ran into the issue again.
I currently use a self-compiled version of the current master branch, which should be 1.6.3.

**Comment by kistitan** [comment] 2016-09-03 22:22
Thank you for testing it!
It's a tricky one.
I will take a look asap.

**Comment by malachid** [comment] 2016-09-03 23:08
This one is actually a high priority for me personally as I generally uninstall any app that doesn't remember my password.

**Comment by kistitan** [comment] 2016-09-04 19:19
Makes sense...
The problem is I saw the issue also, but cannot reproduce it intentionally. 
So cannot debug it.
I did not find anything in the code that would make that happen, other than expired refresh-token but that is also unlikely.
I added some additional log to see whats happening if it happens, but until I cannot do more than wait and check the code again.

If someone has a stable reproduce scenario please let me know.

@malachid 
I do understand that, it is indeed annoying. In the meanwhile you can use 1.4 version.

**Comment by kistitan** [comment] 2016-09-04 20:45
I am playing around for hours now, but cannot reproduce with 1.6.3 ...

**Comment by kistitan** [comment] 2016-09-04 21:01
@Seelenoede 
@malachid 
can you confirm you can still face the issue?
If yes would you let me know if you felt like helping me out with testing? 
So I can make you a specific build that produces external log file that can give me some hints what's going on when the issue happens.
Thank you

**Comment by malachid** [comment] 2016-09-04 23:46
The last time I saw it, I had upgraded, used the app, then on hitting the back arrow to exit the app it asked me to log in.  I do not have consistent repro steps at this moment.  I can install a logcat version if you like.

**Comment by Seelenoede** [comment] 2016-09-05 07:06
@kistitan, I am not at home this week, so I don't think I am a big help at testing.
If you haven't found until next week, I am happy to help tough.

**Comment by kistitan** [comment] 2016-09-05 08:26
Hi there,

@Seeleonede
@malachid

Thanks for your your contribution.
Actually the problem was with 1.6.2 is that settings could have been saved and load for a null user, after upgrade the issue can occur exactly once, after in-theory it should work normally.
So let's wait if for any of us it occurs again, until that  I put this issue on hold.
To be the safe side you can also clear user data for 1.6.3, log in and after it should work normally.
if it doesn't, please let me know.

**Comment by malachid** [comment] 2016-09-05 14:47
As I was getting ready to clear the data, I noticed I am currently on 1.6.2. I thought the app used to auto- update?

**Comment by kistitan** [comment] 2016-09-06 09:46
@malachid 
No it does not. We send around manual notification, with the upgrade link.

For auto update we should use some framework like hockey or something, what is actually a good idea, and should be on our list.

**Comment by kistitan** [comment] 2016-09-06 09:47
Ok guys, so I haven't seen the issue since on 1.6.3, so I close this issue, but please keep your eyes open (so do i) and I will reopen it the very first moment we can see it again 

Thank you!

**Comment by kistitan** [comment] 2016-09-08 11:00
Issue occurred again... might be a token expiration but still would be too early.
Unfortunately logs were not helpful...

I feel bad about this, but I will eventually track down :)

**Comment by kistitan** [comment] 2016-09-12 13:08
I managed to fix the issue.
The user has been logged out buy a delayed thread, that we use not to lo out the user during for example image upload, when the app is sent to the background, but probably will be visited again.
Here I did not check correctly the user settings for password always preference.
So it was a bug to fix, however it is still very unclear why that background thread started.
That I will investigate further, but the issue seems to be fixed now.

**Comment by kistitan** [comment] 2016-09-21 13:47
Finally fixed fully in 1.7

**Closed by kistitan** 2016-09-21 13:47 UTC
Labels: bug, priority medium, waiting for release

**Comment by malachid** [comment] 2016-09-21 17:31
Confirmed that it did not ask for password on update

**Comment by johnbaku** [comment] 2016-09-21 18:26
@malachid thanks for the update!
