### ISSUE TITLE
App does not open from notification

### ISSUE THREAD

**Issue by Mistress-Dalgato** [fetlife/android#515] opened 2019-01-03 06:59 UTC
So with the app for android I have noticed 2 issues, one when i get notifications and then click them it doesn't bring up the app. Also i cant delete messages via the app, cany anyone help?

**Comment by kistitan** [comment] 2019-01-20 22:09
Hey @Mistress-Dalgato ,

I apologize for the late reply.
Deleting messages indeed not possible at the moment.

About the notification issues, may I ask if it is all kind of notifications (new messages, likes, etc) or only with some particular ones (e.g. new versions).

Can you please help us out with your App version and your device's Android OS version?

Thanks a lot

**Comment by Mistress-Dalgato** [comment] 2019-01-21 19:21
Yes it's for all notifications , I click on it and it takes me nowhere. I literally have to go and figure out like for example if somebody comments not a discussion I followed I literally have to try and figure it out manually as for my Android version I have 8.0.0 what it looks like for the app version I have to point 17.6 I know there's been a few times that it's updated and then a few times that for whatever reason had to roll back because my messages won't delete from the app after I deleted them directly via the website online

**Comment by kistitan** [comment] 2019-02-03 22:41
@Mistress-Dalgato 
Still sorry for the late reply, we are working on a new version, but did not forget about this issue.

We unfortunately did not find any reason for this issue.
In theory app should be brought in the front, like how it does on our test devices.

The only respond when it should not happen, when the App gets force closed. 
Force close can be initiated from the settings, or based on our investigation some manufacturer's phones and some battery savings app do it by default.

In the next version we will try to add an extra wake up signal to avoid those cases, but for the time being, you might want to check if your phone has any built in pr battery savers settings for excluding apps from force closing

**Comment by kistitan** [comment] 2019-04-16 09:20
Hi @Mistress-Dalgato,

May I ask you had the chance to upgrade your app in the meantime?
Did the issue go or is it still reproducable?

Thanks you
Dreamlite

**Comment by kistitan** [comment] 2019-05-08 08:32
Closing this issue for now due to inactivity.

If the issue would still occur, there is a chance it happens, because of some device manufacturer by default force close inactive apps, that stops them being able to receive messages.

In order to check if this is the cease, please read this blog post:
https://onesignal.com/blog/manufacturers-interfere-with-reliable-notifications/

Step by step solution for affected device can be found here too:
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#section-the-app-is-force-stopped

If nothing helps, please feel free to reopen this issue and let us know about.

Thank you

**Closed by kistitan** 2019-05-08 08:32 UTC
Labels: bug
