### ISSUE TITLE
Group Post Notifications open in browser

### ISSUE THREAD

**Issue by impishmeuk** [fetlife/android#469] opened 2018-07-15 11:44 UTC
When tapping on group post notifications they open in Chrome instead of the app, is this supposed to happen?

**Comment by kistitan** [comment] 2018-08-07 09:27
@impishmeuk 

Sorry for the late reply,
In general it should not happen, but we aware of some cases when the group information do not arrive to the phone so we have to open the notification externally.

Can you please let us know if it indeed happens only time to time or it always happen for you like that?

Thank you

**Comment by impishmeuk** [comment] 2018-08-08 14:51
It's every notification that's loading in chrome rather than the app

**Comment by kistitan** [comment] 2018-09-18 06:31
Sorry again, for the huge delay, in replying.
We could not reproduce this issue yet, but we are looking into our notifications system right now due to other issues.
Hopefully we will find the solution for this too.

Thank you very much for your patience.

**Comment by kistitan** [comment] 2018-10-03 12:03
Closing this due to duplication.
Please follow this:
https://github.com/fetlife/android/issues/488

**Comment by kistitan** [comment] 2019-03-07 14:41
Hi there,

We did improvement in this area.
Can you please confirm the issue is gone for the followings:
- notifications about new discussions
- mentions in followed discussions
- comments in followed discussions.

Thanks a lot

**Comment by kistitan** [comment] 2019-04-16 09:09
Closing this issue for now, please feel free to reopen in case the issue occurred again for the above cases.

Thank you

**Closed by kistitan** 2019-04-16 09:09 UTC
Labels: bug
