### ISSUE TITLE
New android update

### ISSUE THREAD

**Issue by Lilchik2086** [fetlife/android#492] opened 2018-09-23 13:50 UTC
New android update on the Samsung J7 prime has stopped the fetlife app from working at all.  anyone have any thoughts or a fix on this?

**Comment by johnbaku** [comment] 2018-09-24 16:16
@kistitan mind looking into this please?

**Comment by kistitan** [comment] 2018-09-25 09:01
@Lilchik2086 

Can you please help me out, what is actually happening?
Does the app crash? Or just does not start?

May I ask what is your OS version?

Thanks

**Comment by Benedictum** [comment] 2018-10-16 05:13
I'm on android 9 on a pixel 2 xl and I can confirm most app functionality is not working since Android 8. I can view profiles of friends but going to feed, stuff you love, etc shows a red loading circle for a half second in upper right then a mostly blank screen. Using 2.16 or 2.17.13. Wifi or cellular.

**Comment by kistitan** [comment] 2018-10-23 08:31
Hi @Benedictum 

Still could not reproduce it on our test devices.
Still trying to figure out something.

Sorry for the inconveniences

**Comment by kistitan** [comment] 2018-10-29 18:40
thanks for letting us know... closing it for now.

**Closed by kistitan** 2018-10-29 18:40 UTC
Labels: question
