### ISSUE TITLE
Setting content is missing 

### ISSUE THREAD

**Issue by IAmAdulting** [fetlife/android#449] opened 2018-06-21 13:09 UTC
When I go to settings, there's no options.

**Comment by kistitan** [comment] 2018-06-22 07:38
Hi @IAmAdulting ,

Would you mind increasing your display brightness and trying to click on the screen?
We got reports that on some devices the setting screen color settings are ignored, and similar colors are used for the text as the backgrounds.
I wonder if that is the case.

Thank you

**Comment by kistitan** [comment] 2018-10-31 10:16
Closing this issue now, as we have no new user response, and we cannot reproduce anymore our styling issue.
It happens on older Samsung devices and we did not find a proper solution yet, but with OS update on the devices solved the issue.

Please reopen if the issue occurred again.

**Closed by kistitan** 2018-10-31 10:16 UTC
Labels: question
