### ISSUE TITLE
Conversation spontaneous refresh

### ISSUE THREAD

**Issue by kamakazi414** [fetlife/android#553] opened 2019-05-06 15:16 UTC
My phone updated to the new Android app, v 3.0.

I've been struggling with it ever since. The messaging section is now mimicking the desktop version. On the surface, that's not so bad. The big problem is that as I type, the page refreshes all on it's own, destroying everything I've written to that point. It's useless to try and retype the message as the page refreshes again and again. 

The only thing I was able to do to complete my message was to copy all to my clipboard, and paste it back after the refresh and press the say it button quickly afterward. Then, I'd have to continue my comments on a new message, repeating the same copy all to the clipboard as I progressed. It's annoying.

To be honest, I loved the 2.x Android version of messaging far better. I've lost features I've come to depend upon in the Android version that I don't have in the desktop version.

I'd be happy to expand upon my opinion if you are interested.

In the meantime, please fix this refresh problem ASAP. It's most annoying, making it difficult to maintain continuity with my submissive. 

Regards,

Rich

(FL name: Kamakazi)

**Comment by kamakazi414** [comment] 2019-05-07 11:38
I don't know if this has anything to do with the question, but I use a Blutooth keyboard to write the bulk of my messages, rather then the onscreen keyboard. My messages are often long and detailed, taking a fair amount of time to compose.

**Comment by FernandoMiguel** [comment] 2019-05-07 11:40
I agree... the new webview design has some advantages but it is worse than the previous version
it is much slower,  you cant send messages offline, and opening notifications will open the All Messages window instead of the message you just received

**Comment by kistitan** [comment] 2019-05-07 11:48
Hi guys,

Thanks a lot for giving us these feedback.
I will let our designer and web developer know about them.

Dreamlite

**Comment by kistitan** [comment] 2019-05-07 12:08
@kamakazi414 

May I ask what kind of device and OS version do you use.
Would you mind testing if the same refresh issue happening in your browser too?

Thank you

**Comment by nielsenramon** [comment] 2019-05-07 12:26
@kamakazi414 @FernandoMiguel Thanks for reporting these issues, sorry you are encountering them :-/. We are looking into solving the following things:

- Opening notifications will open the All Messages window instead of the message you just received.
- Page should not be refreshing at all.
- Storing what you typed in the input field.

Sadly none of these issues came up during the beta :-/

**Comment by FernandoMiguel** [comment] 2019-05-07 13:17
i didnt get any DM during the beta @nielsenramon , so i didnt use it much

**Comment by kamakazi414** [comment] 2019-05-07 15:15
Attached is my phone info you asked for. In all the years I've used the site, I've never experienced this issue before. I'll be happy to do whatever testing you'd like me to do. I am a software engineer so I know the importance of testing. Be aware, I am now writing my message in another text editor, then copying and pasteing to your app. This tells me it's not the size of the message, but rather the duration spent in typing the message. Some sort of time out is triggering the refresh. Another feature lost in the upgrade, independent scroll regions from text box and the rest of the conversation. This is useful if I need to refer to some thing written earlier in the conversation while I am typing.RegardsRichhttp://richardverry.com
-------- Original message --------From: kistitan <notifications@github.com> Date: 5/7/19  8:08 AM  (GMT-05:00) To: fetlife/android <android@noreply.github.com> Cc: kamakazi414 <kamakazi414@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [fetlife/android] Conversation spontaneous refresh (#553) @kamakazi414
May I ask what kind of device and OS version do you use.
Would you mind testing if the same refresh issue happening in your browser too?
Thank you

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/fetlife/android/issues/553#issuecomment-490052225",
"url": "https://github.com/fetlife/android/issues/553#issuecomment-490052225",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kistitan** [comment] 2019-05-07 15:42
Hi @kamakazi414 

**About the reported issue:**
Thanks for the information about the web browser experience.
That helps us to confirm it is probably webview related issue, so we know which area should we investigate further

**About the layout changes:**
> Another feature lost in the upgrade, independent scroll regions from text box and the rest of the conversation. This is useful if I need to refer to some thing written earlier in the conversation while I am typing.

Thanks also for giving us this feedback. We are eager to hear opinion about the App, as it is the key information that we need to improve. 

cc/ @nielsenramon 

**About the device information**
Unfortunately your message via email came through a bit fragmented, and the device information got lost.
Would you mind posting it again directly to the GitHub issue.

thanks a lot again
Dreamlite

**Comment by kamakazi414** [comment] 2019-05-07 16:04
The phone info was in a screen grab of my phone in the form of a jpg. 

The phone is a Samsung Galaxy S8, model SM-G950U
Hardware version rev 1.0

OS version is: G950USQS5CSB1

Android v 8.0
Samsung v 9.0
Kernal v 4.4.78

I hope this helps.

**Comment by kistitan** [comment] 2019-05-07 20:20
@FernandoMiguel 

> opening notifications will open the All Messages 

We tried to reproduce this on our test devices, but so far it works perfectly.
May I ask if you have this issue constantly or only it happens sometimes?

**Comment by FernandoMiguel** [comment] 2019-05-07 20:26
@kistitan every single time
pixel 3xl with android Q
multiple browsers installed , but non set as default

**Comment by kistitan** [comment] 2019-05-08 08:11
@FernandoMiguel @kamakazi414 

We created a special logging build, and we also changed the way we open screens from notifications, so we are also curious if that issues has been solved for you @FernandoMiguel or not.
The other issues wont't be solved (refresh), but with the logs we might get some insight.

So if you can afford your time for helping us out, please: 

1. download the attached .zip file
2. rename the downloaded file from .zip to .apk
3. if it is not there already, move or copy the .apk file to your Android device
4. install the .apk file on your device, by locating it with your download or file browser app and executing it (please follow the on device instructions for the installation)
5. reproduce the issue, or wait until it is happening again
6. after it happened again, please open your side menu and select the new menu item: Share Logs
7. Please send the logs to krisztian@fetlife.com

Thank you
[fetlife-3.0.2-beta.1+1557299758.zip](https://github.com/fetlife/android/files/3156272/fetlife-3.0.2-beta.1%2B1557299758.zip)

**Comment by kistitan** [comment] 2019-05-08 14:23
@FernandoMiguel 

Yes, unfortunately we do not support offline mode any more with the new webview based approach.
But thanks for giving us feedback about, it is important to know about these use-cases so we can take them into consideration. 

cc @nielsenramon

**Comment by kistitan** [comment] 2019-05-08 14:24
@FernandoMiguel

Yes, unfortunately we do not support offline mode any more with the new webview based approach.
But thanks for giving us feedback about, it is important to know about these use-cases so we can take them into consideration.

cc @nielsenramon

**Comment by FernandoMiguel** [comment] 2019-05-08 21:28
With the debug version I get the issue of fail to connect to the server

**Comment by FernandoMiguel** [comment] 2019-05-08 21:30
Cleared the app data and login again and it's fine.
I don't see the menu to send logs

**Comment by FernandoMiguel** [comment] 2019-05-08 21:32
Never mind... Right on the top... Duh

**Comment by kistitan** [comment] 2019-05-09 12:28
@kamakazi414 

I reply here on your email, to make it public as it might be useful for others.
Thank you for helping us out figuring out the root cause of the issue.

You told that the unwanted refresh happened when your bluetooth keyboard is disconnected.
That would explain the logs why the OS started to recreate the screen out of nowhere.

Unfortunately I have a good and a bad news.
The bad news is, that as the OS triggers the view creation, we cannot do anything about it in short term.
We simply have to rebuild the view, and as we do not have the typed text available at client side, we cannot even store it.

The good news is, that our web developers will work on  finding the way to save the already typed text so it will be reserved in case of the UI is rebuilt.

We are sorry about the inconveniences
Dreamlite

**Comment by kistitan** [comment] 2019-05-09 12:31
@FernandoMiguel 

Do I understand correctly that with the sample build, the new message notification open the actual conversation correctly?
If not, or you need help to test, let me know if you would like to me to send you a private message.

Thank you

**Comment by kamakazi414** [comment] 2019-05-09 14:30
Thank you for your response.

Just to clarify, the disconnect of the bluetooth keyboard can be
unintentional or momentary. Even as little as a millisecond is enough to
trigger the refresh. My other apps DO NOT exhibit this behavior. I use my
bluetooth keyboard frequently.

Since the developers will need some time to build the view, can you send me
the latest 2.x version so I can resume my FL life on my android device?
Using the android app is my primary use of the platform, and without it, I
am seriously handicapped.

Once you resolve the issue, I will happily install the 3.x version.

In the meantime, as of this morning, I cannot log into my account via the
Android app. Typing my valid ID and pwd simple sits with the message
"Logging you In...." without ever coming back with a result, or until the
beta app crashes, which is frequent. I can access the platform using a
standard browser.

—

Richard Verry, Writer and Artist
https://richardverry.com


“I don’t care if a reader hates one of my stories, just as long as they
finish the [damn] book.” ~Roald Dahl

**Comment by FernandoMiguel** [comment] 2019-05-09 15:24
@kistitan 
> Do I understand correctly that with the sample build, the new message notification open the actual conversation correctly?
I have not received any new DM since i installed the beta

**Comment by kistitan** [comment] 2019-05-10 08:04
@kamakazi414 

I replied via email about downgrade instructions and one more test version.

Thank you

**Comment by kistitan** [comment] 2019-05-10 08:07
@FernandoMiguel 

If you send me an email with your user name via email, I can send you a PM.

Thank you

**Comment by kistitan** [comment] 2019-05-24 18:22
Splitting these two issues now to have a clear follow up possible.

Summary of issue reported by @kamakazi414 :
When a bluetooth keyboard is used and the connection got lost, the screen get refreshed and the already typed notification is lost.

We do not have the proper set-up to be able to reproduce the issue, but based on what we see, the used Android OS automatically rebuilds the UI after loosing the connection to the keyboard as a configuration change.
We tried to disable configuration changes on this specific case, but it did not change the bahviour.

This issue seems be a result of unfortunate circumstances and we cannot fix as a bug, however we added a new feature request of our todo list of saving the already typed message at server side, so even if the UI rebuilds the message is not lost.

Having a separate issue tracker for that feature, I am closing this issue now.
Please feel free to come back to us in case of any further question.

Issue reported by @FernandoMiguel 
When a notification about a new message is clicked the appropriate conversation is not opened, but the inbox screen is displayed instead.

We did deep research on it, and we could not reproduce the issue on our test devices, not even with Android Q beta, that OS version is used by the user.
We created a separate debug version to see what is going on the actual devices, but also the logs from the OS callbacks claims that the appropriate screen is loaded, but it is still not visible for the user.

As we ran out of any further option to investigate further, we agreed to close this issue now, asking @FernandoMiguel to keep an eye on this issue, and let us know how does it go after a stable Android version is installed.


Please feel free to ask if you had any further questions.

**Closed by kistitan** 2019-05-24 18:22 UTC
Labels: bug
