### ISSUE TITLE
app does not show All conversations

### ISSUE THREAD

**Issue by miyuu-tomasu** [fetlife/android#219] opened 2016-11-24 22:23 UTC
The app currently only shows Conversations that have been replied to. 
Suggestion: Please might we have an option to show **All** Conversations? 
(All Conversations are important to those of us who utilise messaging for M/s tasks).

**Comment by kistitan** [comment] 2016-11-25 20:49
Hi @miyuu-tomasu 

Thank you for reporting this issue.
You are right that App does not show the conversations that are started from the website and not yet replied to. But let me know conversations that are started from the App itself are visible.

It is a valid feature request and we add it to our todo list. 

Thank you for your support

**Comment by miyuu-tomasu** [comment] 2016-11-26 00:56
Hi @kistitan 
Yes that's right:  conversations that are started from the App itself remain visible. 

Interestingly, if the conversation is a short, one line message the actual message text becomes the subject and it sends without a hiccup, but if i attempt to initiate a conversation with multiple paragraphs from the app v2.0.0, it returns a error pop-up 'Connection failed. Please try again later' and the message does not send... i suspect the app is trying to put the whole message into the subject box and this is what causes the failure? 

As such, when using the app i've discovered it is best to initiate a conversation with a short, one line text in the first instance, [ that becomes the subject ], then i can follow up the initial message with a multi paragraph message subsequently with no connection failures.

**Comment by kistitan** [comment] 2016-11-27 16:04
hi @miyuu-tomasu,

The app indeed tries to use the first message as a subject. The reason behind that conversations and chat system has a slight different approach but as of now we use the same system for that.
We are however plan to improve in the future.

The connection issues however is not as it supposed to be.
We used to have this issue on older version but now we simple truncate the first message before we send it to the server.
Can you confirm that you can continiously reproduce the long text cause connection issues even with our latest version (2.0.0). I made a quick test but for me it worked without any issue.

Thanks a lot

**Comment by kistitan** [comment] 2016-12-07 21:39
Long subject issue is a regression bug.
Will be fixed again in the next version.
Issue will be kept open as a feature request for all conversations.

**Comment by miyuu-tomasu** [comment] 2016-12-13 20:53
The long, new message issue is resolved in v2.1.0 however, when a new message posted within the app that message disappears from the conversations list until there is a reply

**Comment by kistitan** [comment] 2016-12-14 08:58
@miyuu-tomasu 
Thank you for reporting this issue and testing our preview version.

Issue has been fixed and will be released soon

**Comment by kistitan** [comment] 2016-12-14 12:29
@miyuu-tomasu 
That reported issue should be fixed now in version 2.1.2.
Thank you

**Closed** 2017-06-01 09:09 UTC
Labels: enhancement, Priority 4
